export const adminConstants = {
  LOGIN_TITLE: "Lets Sign you in",
  SIGN_IN: "Let's get started",
  SIGN_IN_YOU: "Hey, good to see you",
  EMAIL: "Email",
  PASSWORD: "Password",
  FORGOT_PASSWORD: "Forgot password ?",
  PROVIDER: "Provider",
  ADMIN: "Admin",
  PROFILE: "Profile",
  SETTING: "Setting",
  LOGOUT: "Logout",
  POST_AUTH_LOGO: "Post Auth Logo",
  SEND_VERIFICATION_LINK: "Send Verification Link",
  BACK_TO_SIGNIN: "Back to Sign in",
  UPDATE_PASSWORD: "Update Password",
  NEXT: "Next",
  ENTER_PASSWORD: "Enter new password",
  CONFIRM_NEW_PASSWORD: "Confirm password",
  PASSWORD_DO_NOT_MATCH: "Passwords do not match",
  RESEND_OTP: "Resend OTP",
  SEND_OTP: "Send OTP",
  INVALID_EMAIL: "Invalid email address",
  EMAIL_REQUIRED: "Please enter the email",
  PASSWORD_REQUIRED: "Please enter the password",
  LINK: "Link send successfully",
  NEW_PASSWORD_REQUIRED: "New password is required",
  PASSWORD_LENGTH: "Password must be at least 8 characters long",
  CONFIRM_NEW_PASSWORD_REQUIRED: "Confirm password is required",
  PASSWORD_MUST_MATCH: "New Password and Confirm Password must same",
  PASSWORD_UPDATED_SUCCESSFULLY: "Password updated successfully",
  ENTER_VALID_CREDS: "Please enter valid credentails.",
  PATIENT: "Patient",
  PATIENTS: "Patients",
  USERS: "Users",
  ADD_MEDICATION: "Add Medication",
  ADD_USER: "Add User",
  PROVIDER_USER: "Provider User",
  STAFF_USER: "Staff User",
  ChECK_PROVIDER: "provider",
  CHECK_STAFF: "staff",
  PROFILE_PHOTO: "Profile Photo",
  FIRST_NAME: "First Name",
  FIRSTNAME: "firstName",
  LAST_NAME: "Last Name",
  LASTNAME: "lastName",
  SAVE: "Save",
  CONTACT_NUMBER: "Contact Number",
  ROLE: "Role",
  STATUS: "Status",
  PLACEHOLDER: "Placeholder",
  SELECT_AN_OPTION: "Select an option",
  SELECT_SPECIALITY_TYPE: "Select Speciality Type",
  ENTER_FIRST_NAME: "Enter First Name",
  ENTER_LAST_NAME: "Enter Last Name",
  ENTER_CONTACT_NUMBER: "Enter Contact Number",
  ENTER_EMAIL: "Enter Email",
  SELECT: "Select",
  ACTIVE: "Active",
  INACTIVE: "Inactive",
  ADD_STAFF: "STAFF",
  FIRSTNAME_MISSING: "Please enter first name",
  LASTNAME_MISSING: "Please enter last name",
  EMAIL_MISSING: "Please enter email id",
  CORRECT_EMAIL: "Please enter valid email id",
  CONTACT_MISSING: "Please enter contact number",
  ROLE_MISSING: "Please select a role",
  NO_USERS_FOUND: "No Users Found",
  NO_PATIENTS_FOUND: "No Patients Found",
  DASHBOARD: "Dashboard",
  PROVIDERGROUP: "Provider Groups",
  MASTER: "Data & Catalog",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",

  ADD_PROVIDER: "Add Provider",
  PROVIDER_TYPE_MISSING: "Please select provider type",
  SPECIALITY_MISSING: "Please select speciality",
  NAME_MISSING: "Please enter name",
  NPI_NUMBER_MISSING: "Please enter NPI number",
  PHONE_NUMBER_MISSING: "Please enter phone number",
  GROUP_NPI_MISSING: "Please enter group NPI number",
  WORK_LOCATION_MISSING: "Please select work location",
  BASIC_ACCOUNT_PROFILE_DATA: "Basic Account Profile Data",
  AREAS_OF_FOCUS: "Sub - Specialities/Areas Of Focus",
  NAME_SUBSPECIALITY: "subSpeciality",
  ENTER_AREAS_OF_FOCUS: "Enter Sub - Specialities/Areas Of Focus",
  HOSPITAL_AFFECTION: "Hospital Affilation",
  NAME_HOSPITAL_AFFILATION: "hospitalAffilation",
  ENTER_HOSPITAL_AFFECTION: "Enter Hospital Affilation",
  AGE_GROUP_SEEN: "Age Group Seen ",
  NAME_AGE_GROUP_SEEN: "ageGroupSeen",
  LANGAGE_SPOKEN: "Languages Spoken",
  NAME_LANGUAGE_SPOKEN: "languageSpoken",
  EMP_REFERRAL_NUMER: "Provider Employment Referral Number",
  NAME_REFERRAL_NUMBER: "referralNumber",
  ENTER_EMP_REFERRAL_NUMER: "Enter Provider Employment Referral Number",
  ACCEPT_NEW_PATIENTS: "Accept New Patients",
  NAME_ACCEPT_NEW_PATIENTS: "acceptNewPatients",
  ACCEPT_CASH_PAY: "Accept Cash Pay",
  NAME_ACCEPT_CASH_PAY: "acceptCashPay",
  PRIOR_AUTORIZATION: "Prior Authorization",
  NAME_PRIOR_AUTORIZATION: "priorAuthorisation",
  SECOND_OPINION: "Second Opinion",
  NAME_SECOND_OPINION: "secondOpinion",
  ACTUAL_SPECIALITY_CARE_SERVICE: "Actual Speciality Care Service",
  NAME_ACTUAL_SPECIALITY: "acuteSpeciality",
  INSURANCE_VERIFICATION: "Insurance verification",
  NAME_INSURANCE_VERIFICATION: "insuranceVerification",
  PROVIDER_BIO: "Provider Bio",
  BIO: "Bio",
  NAME_BIO: "bio",
  ENTER_BIO: "Enter Bio",
  EXPERTISE_IN: "Expertise In",
  NAME_EXPERTISE_IN: "expertiseIn",
  ENTER_EXPERTISE: "Enter Expertise",
  WORK_EXPERIANCE: "Education, Work Experience",
  NAME_WORK_EXPERIANCE: "workExperience",
  ENTER_WORK_EXPERIENCE: "Enter Education, Work Experience",
  PROVIDER_TYPE: "Provider Type",
  NAME_PROVIDER_TYPE: "providerType",
  PROVIDER_NPI_NUMBER: "NPI Number",
  SPECIALITY: "Speciality",
  SPECIALITY_SMALL: "speciality",
  SUCCESS_PROVIDER_USER_PROFILE_ADD: "Provider User Added Successfully!",
  SUCCESS_EDIT_PROVIDER_USER_PROFILE_EDIT_MESSAGE:
    "Provider Group Updated Successfully!",

  PROVIDER_PROFILE: "Provider Profile",
  SELECT_SPECIALITY: "Select Speciality Type",
  GENDER: "Gender",
  SELECT_GENDER: "Select Gender",
  NPI_NUMBER: "NPI Number",
  NAME_MPI_NUMBER: "npiNumber",
  ENTER_NPI_NUMBER: "Enter NPI Number",
  GROUP_NPI_NUMBER: "Group NPI Number",
  NAME_GROUP_NPI_NUMBER: "groupNpiNumber",
  ENTER_GROUP_NIP_NUMBER: "Enter Group NPI Number",
  PROVIDER_PHONE_NUMBER: "Provider Contact Number",
  NAME_PHONE_NUMBER: "phoneNumber",
  ENTER_PROVIDER_PHONE_NUMBER: "Enter Phone Number",
  OFFICE_FAX_NUMBER: "Office Fax Number",
  NAME_FAX_NUMBER: "faxNumber",
  ENTER_FAX_NUMBER: "Enter Fax Number",
  LICENSED_STATE: "Licensed State (s)",
  COUNTY: "Country",
  NAME_LICENSED_STATE: "licensedState",
  LICENSE_NUMBER: "License Number",
  NAME_LICENCE_NUMBER: "licenseNumber",
  ENTER_LICENSE_NUMBER: "Enter License Number",
  INSURANCE_ACCEPTED: "Insurance (s) Accepted",
  NAME_INSURANCE_ACCEPTED: "insuranceAccepted",
  YEAR_OF_EXPERIANCE: "Year Of Experience",
  NAME_YEAR_EXPERIANCE: "yearOfExperience",
  TAXONOMY_NUMBER: "Taxonomy Number",
  NAME_TAXONOMY_NUMBER: "taxonomyNumber",
  ENTER_TAXONOMY_NUMBER: "Enter Taxonomy Number",
  WORK_LOCATIONS: "Work Locations",
  NAME_WORK_LOCATION: "workLocations",
  ADMIN_PROFILE: "Admin Profile",
  NAME: "Name",
  EMAIL_ID: "Email Id",
  PHONE_NUMBER: "Office Phone Number",
  USER_TYPE: "User Type",
  CHANGE_PASSWORD: "Change Password",
  PERMISSION: "Permission",
  DESCRIPTION: "Description",
  status: "status",
  ENABLE: "Enable",
  DISABLE: "Disable",
  CURRENT_PASSWORD: "Current password",
  NEW_PASSWORD: "New password",
  CHANGED_PASSWORD: "Change Password",
  CHANGE: "Change",
  BASIC_INFORMATION: "Basic Information",
  BASIC_ACCOUNT_DATA: "Basic Account Profile Data",
  SUB_SPECIALTIES: "Sub - Specialties / Areas Of Focus",
  HOSPITIAL_AFFAIR: "Hospital Affilation",
  YEAR_OF_EXPERIENCE: "Year Of Experience",
  PROVIDER_EMPLOYEMNT: "Provider Employment",
  WORK_EXPERIENCE: "Work Experience",
  YES: "Yes",
  NO: "No",
  EMAILID: "Email",
  ADMINEDIT: "adminEdit",
  PROVIDEREDIT: "providerEdit",
  USER: "User",
  LICENESE_NUMBER: "License Number",
  WORK_LOCATION: "Work Location",
  SEARCH_HERE: "Search Here",
  ADD_LOINC_CODE: "Add LOINC Code",
  EDIT_LOINC_CODE: "Edit LOINC Code",
  ADD_ICD_CODE: "Add ICD 10 Code",
  ADD_PROCEDURE_CODE: "Add CPT Code",
  EDIT_ICD_CODE: "Edit ICD 10 Code",
  ADD_CPT_CODE: "Add CPT Code",
  EDIT_CPT_CODE: "Edit CPT Code",
  ADD_HCPCS_CODE: "Add HCPCS Code",
  EDIT_HCPCS_CODE: "Edit HCPCS Code",
  ADD_DRUG_CATALOG: "Add Drug Catalog",
  EDIT_DRUG_CATALOG: "Edit Drug Catalog",
  CANCEL: "Cancel",
  ADD: "Add",
  EDIT: "Edit",
  PROVIDER_GROUP_NAME: "Name",
  WEBSITE: "Website",
  PHYSICAL_ADDRESS: "Physical Address",
  PRACTICE_FAX_NUMBER: "Practice Fax Number",
  BILLING_ADDRESS: "Billing Address",
  PROVIDER_GROUP_HOURS: "Provider Group Hours",
  ADD_NEW_PROVIDER_GROUP: "Add New Provider Group",
  EDIT_PROVIDER_GROUP: "Edit Provider Group",
  ADD_PROVIDER_LOGO: "Logo",
  ENTER_PROVIDER_GROUP_NAME: "Enter Provider Group Name",
  SPECIALITY_TYPE: "Speciality Type",
  ENTER_EMAIL_ID: "Enter Email id",
  ENTER_WEBSITE: "Enter website",
  ENTER_FAX_ID: "Enter Fax ID",
  FAX_ID: "FAX ID",
  ENTER_DESCRIPTION: "Enter Description",
  ADDRESS_ADDRESS_1: "Address 1",
  ADDRESS_ADDRESS_2: "Address 2",
  ADDRESS_CITY: "City",
  ADDRESS_STATE: "State",
  ADDRESS_COUNTRY: "Country",
  ADDRESS_ZIP_CODE: "Zip Code",
  SAME_AS_PHYSICAL_ADDRESS: "Same as Physical Address",
  PRACTICE_OFFICE_HOURS: "Practice Office Hours",
  OPEN_TIME: "Open Time",
  COLSE_TIME: "Close Time",
  ADD_NEW_LOCATION_LOGO: "Logo",
  LOCATION_NAME: "Name",
  ENTER_LOCATION_NAME: "Enter Location Name",
  LOCATION_ID: "Location ID",
  ENTER_LOCATION_ID: "Enter Location ID",
  INFORMATION: "Information",
  ENTER_INFORMATION: "Enter Information",
  EDIT_LOCATION: "Edit Location",
  ADD_NEW_LOCATION: "Add New Location",
  DEPARTMENT_ID: "Department ID",
  ENTER_DEPARTMENT_ID: "Enter Department ID",
  DEPARTMENT_NAME: "Department Name",
  ENTER_DEPARTMENT_NAME: "Enter Department Name",
  DEPARTMENT_ADMIN: "Department Admin",
  SELECT_DEPARTMENT_ADMIN: "Select Department Admin",
  ADD_NEW_DEPARTMENT: "Add New Department",

  ROLE_NAME: "Role Name",
  ROLE_NAME_MISSING: "Please enter role name",
  ROLE_TYPE_MISSING: "Please select role type",
  PERMISSION_MISSING: "Please select permission",
  ENTER_ROLE_NAME: "Enter role name",
  ROLE_TYPE: "Select Role Type",
  UPLOAD: "Upload",
  PROIVDER_GROUP_NAME: "Provider Group Name",
  SUPPORTED_FORMAT: "Supported formats: csv",
  USER_PROFILE: "User Profile",
  TYPE_TEXT: "text",
  PASSWORDFIELD: "Password",
  EXCLUDE_INACTIVE_PATIENT: "Exclude Inactive Patient",
  ADD_NEW_PATIENT: "Add Patient",

  SETTINGS: "Settings",
  STAFF_USER_PROFILE: "Staff User Profile",
  ACCOUNT_SETTINGS_HEADING: "Account Settings",
  SAVE_CHANGES: "Save Changes",
  RESET: "Reset",
  ADD_PROVIDER_USER: "Add Provider User",
  EDIT_PROFILE: "Edit Profile",
  ADD_STAFF_USER: "Add Staff User",
  EDIT_STAFF_USER: "Edit Staff User",
  PROVIDER_GROUP_FAX_NUMBER: "Provider Group Fax Number",
  EHR_SYSTEM: "EHR System",
  PROVIDER_GROUP_DESCRIPTION: "Provider Group Description",
  PROVIDER_GROUP_OFFICE_HOURS: "Provider Group Office Hours",
  PROVIDER_GROUP_INFORMATION: "Provider Group Information",
  SUCCESS_ADD_PATIENT_MODAL: "Patient Details Added Successfully",
  SIGN_UP: "Sign Up",
};
