export const patientConstants = {
  PATIENT: "Patient",
  MY_APPOINTMENTS: "My Appointments",
  TEST_YOUR_DEVICE: " Test Your Device",
  PAST_APPOINTMENTS: " Past Appointments",
  SCHEDULE_APPOINTMENT: "Schedule Appointment",
  SCHEDULE_NEW_APPOINTMENT: "Schedule New Appointment",
  VISIT_TYPE: "Visit Type",
  APPOINTMENT_TYPE: "Appointment Type",
  LOCATION: "Location",
  SPECIALITIES: "Specialities",
  PROVIDER: "Provider",
  DATE_AND_TIME: "Date & Time",
  INSURANCE_TYPE: "Insurance Type",
  REASON_FOR_APPOINTMENT: "Reason For Appointment",
  BOOK_APPOINTMENT: "Book Appointment",
  PRIMARY_INSURANCE: "Primary Insurance",
  SECONDARY_INSURANCE: "Secondary Insurance",
  PATIENT_APPOINTMENT_NOTE: "Patient Appointment Note",
  APPOINTMENT_REASON_CANCELLATION: "Please Enter reason for the appointment cancellation",
  FIRST_NAME:'First Name',
  MIDDLE_NAME:'Middle Name',
  LAST_NAME:'Last Name',
  DOB:'Date Of Birth',
  GENDER:'Gender',
  MARITAL_STATUS:'Marital Status',
  TIME_ZONE:'Time Zone',
  LANUAGE:'Language',
  SSN:'SSN',
  RACE:'Race',
  ETHINICITY:'Ethinicity',
};
