export const providerConstants = {
    PRACTICE_PROVIDER_REVENUES: 'Practice or Provider Revenues',
    VIEW_DETAILS: 'View Details',
    UPCOMING_APPOINTMENTS: 'Upcoming Appointments',
    VIEW_ALL: 'View All',
    ACCOUNTS: 'Accounts Receivable Aging',
    REPORTS: 'Reports',
    RECENTLY_ADDED_PATIENT: 'Recently Added Patient',
    NEW_PATIENT: 'Add Patient',
    SUPER_BILL: 'Super Bill',
    PATIENT_NAME: 'Name',
    PATIENT_ID: 'Patient ID',
    PATIENT_DOB: 'DOB',
    MARITAL_STATUS: 'Marital Status',
    RENDERED_PROVIDER: 'Rendered Provider',
    SSN_NUMBER: 'SSN Number',
    INSURANCE_AVAILABLE: 'Insurance Available',
    SEARCH_ICD_CODE: 'Search ICD Code',
    VISIT_DATE: 'Visit Date',
    VISIT_TIME: 'Visit Time',
    VISIT_TYPE: 'Visit Type',
    SERVICE_LOCATION: 'Service Location',
    PLACE_OF_SERVICE: 'Place of Service',
    SERVICE_STATE: 'Service State',
    CHIEF_COMPLAINT: 'Chief Complaint',
    FIRST_NAME: 'First Name',
    LAST_NAME: 'Last Name',
    NPI_NUMBER: 'NPI Number',
    CONTACT_NUMBER: 'Contact Number',
    EMAIL_ID: 'Email Id',
    STREET: 'Street',
    CITY: 'City',
    STATE_PROVINCE_AREA: 'State/province/area',
    ZIP_CODE: 'Zip Code',
    REFERRING_PROVIDER_NAME: 'Referring Provider Name',
    REFERRING_PROVIDER_NPI_NUMBER: 'Referring Provider NPI Number',
    PULL_FROM_EHR: 'Pull From EHR',
    APPLY: 'Apply',
    PROCEDURE_CODE: 'Procedure Code',
    DIAGNOSIS_CODE: 'Diagnosis Code',
    PROVIDER_DETAILS: 'Provider Details',
    PATIENT_DETAILS: 'Patient Details',
    VISIT_DETAILS: 'Visit Details',
    HCPCS_CODE: 'HCPCS Code',
    TOTAL_CHARGES: 'Total Charges',
    COPAY: 'Co-Pay',
    COINSURANCE: 'Co-Insurance',
    PAYMENT: 'Payment',
    AMOUNT: 'Amount',
    SUBMIT_CLAIM: 'Submit Claim',
    PROCESS_SECONDARY_CLAIM: 'Process Secondary Claim',
    ADD_PAYMENT: 'Add Payment',
    CREATE_SUPER_BILL: 'Create Super Bill',
    MODIFY_SUPER_BILL: 'Modify Super Bill',
    SEARCH:'Search',
    DUE_PAYMENT: 'Due Payment',
    PATIENT_LISTING: 'Patient Listing',
    INSURANCE_LISTING: 'Insurance Listing',
    SETTINGS:'Settings',
    PROVIDER: "Provider",
    ADD_AVAILABILITY : 'Add Availability',
    EDIT_AVAILABILITY : 'Edit Availability'
}
export const PORTAL = {
    NAVALACARE:'NAVALACARE',
    PROVIDER:"NAVALAGLOBAL"
}