import { AccountsType } from "../pages/app/provider/common-files/enums"

export const accountsReveivable = (type: AccountsType) => {
    return [
        {
            [type === 'Patient' ? 'patientId' : 'payerId'] : "93683",
            [type === 'Patient' ? 'patientName' : 'payerName'] : [type === 'Patient' ? "Annie Effertz" : 'Monica Geller'],
            '30days': 10,
            '60days': 25,
            '90days': 35,
            '120days': 75,
            'plusdays': 45,
            'total': 155,
        },
        {
            [type === 'Patient' ? 'patientId' : 'payerId'] : "73982",
            [type === 'Patient' ? 'patientName' : 'payerName'] : [type === 'Patient' ? "Monica Geller" : 'Lesley Dobson'],
            '30days': 10,
            '60days': 25,
            '90days': 35,
            '120days': 75,
            'plusdays': 45,
            'total': 155,
        },
        {
            [type === 'Patient' ? 'patientId' : 'payerId'] : "76345",
            [type === 'Patient' ? 'patientName' : 'payerName'] : [type === 'Patient' ? "Eladia Chapin" : 'Annie Effertz'],
            '30days': 10,
            '60days': 25,
            '90days': 35,
            '120days': 75,
            'plusdays': 45,
            'total': 155,
        },
        {
            [type === 'Patient' ? 'patientId' : 'payerId'] : "34598",
            [type === 'Patient' ? 'patientName' : 'payerName'] : [type === 'Patient' ? "Jocelyn vetroves" : 'Eladia Chapin'],
            '30days': 10,
            '60days': 25,
            '90days': 35,
            '120days': 75,
            'plusdays': 45,
            'total': 155,
        },
        {
            [type === 'Patient' ? 'patientId' : 'payerId'] : "23487",
            [type === 'Patient' ? 'patientName' : 'payerName'] : [type === 'Patient' ? "Ryan Weste" : 'Jocelyn vetroves'],
            '30days': 10,
            '60days': 25,
            '90days': 35,
            '120days': 75,
            'plusdays': 45,
            'total': 155,
        },
        {
            [type === 'Patient' ? 'patientId' : 'payerId'] : "94354",
            [type === 'Patient' ? 'patientName' : 'payerName'] : [type === 'Patient' ? "Mary Riddle" : 'Monica Geller'],
            '30days': 10,
            '60days': 25,
            '90days': 35,
            '120days': 75,
            'plusdays': 45,
            'total': 155,
        },
        {
            [type === 'Patient' ? 'patientId' : 'payerId'] : "23764",
            [type === 'Patient' ? 'patientName' : 'payerName'] : [type === 'Patient' ? "Ludo Bagman" : 'Ryan Weste'],
            '30days': 10,
            '60days': 25,
            '90days': 35,
            '120days': 75,
            'plusdays': 45,
            'total': 155,
        },
        {
            [type === 'Patient' ? 'patientId' : 'payerId'] : "92475",
            [type === 'Patient' ? 'patientName' : 'payerName'] : [type === 'Patient' ? "Ron Wisllie" : 'Harry Potter'],
            '30days': 10,
            '60days': 25,
            '90days': 35,
            '120days': 75,
            'plusdays': 45,
            'total': 155,
        },
        {
            [type === 'Patient' ? 'patientId' : 'payerId'] : "29165",
            [type === 'Patient' ? 'patientName' : 'payerName'] : [type === 'Patient' ? "Ginny Weasley" : 'Ron Wisllie'],
            '30days': 10,
            '60days': 25,
            '90days': 35,
            '120days': 75,
            'plusdays': 45,
            'total': 155,
        },
        {
            [type === 'Patient' ? 'patientId' : 'payerId'] : "56328",
            [type === 'Patient' ? 'patientName' : 'payerName'] : [type === 'Patient' ? "Harry Potter" : 'Ludo Bagman'],
            '30days': 10,
            '60days': 25,
            '90days': 35,
            '120days': 75,
            'plusdays': 45,
            'total': 155,
        }
    ]
}