// import { ContentCopy } from "@mui/icons-material";
export const admindata = {
  name: "John Doe",
  avatar:
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkDCKNwDGNiRdm06_IZpv18OWI4oZA_yxtruRFw8LkFnBYSy5_YWuGrHYT9b1CAMTUy9c&usqp=CAU",
};

export const adminprofile = {
  name: "John Doe",
  email: "john@email.com",
  phonenumber: "8978675645",
  usertype: "Admin",
  role: "Super Admin",
  avatar:
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkDCKNwDGNiRdm06_IZpv18OWI4oZA_yxtruRFw8LkFnBYSy5_YWuGrHYT9b1CAMTUy9c&usqp=CAU",
};

export const usersettingcardsdata = {
  user: [
    {
      id: "1",
      firstName: "John ",
      lastName: "Doe",
      lastLogin: "20 Dec 2022 at 02:25PM",
      email: "john@email.com",
      phone: "8978675645",
      role: "Super User",
      type: "Admin",
      status: "Active",
      avatar:
        "https://www.rti.org/sites/default/files/styles/rti_1020x858/public/expert-images/051421_brian_southwell_profile-square_510.jpg?itok=4p6W3k1o",
    },
    {
      id: "2",
      firstName: "Peter ",
      lastName: "Parker",
      lastLogin: "20 Dec 2022 at 02:25PM",
      email: "john@email.com",
      phone: "8978675645",
      role: "Admin",
      type: "Admin",
      status: "Pending",
      avatar:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkDCKNwDGNiRdm06_IZpv18OWI4oZA_yxtruRFw8LkFnBYSy5_YWuGrHYT9b1CAMTUy9c&usqp=CAU",
    },
    {
      id: "3",
      firstName: "John ",
      lastName: "Swith",
      lastLogin: "20 Dec 2022 at 02:25PM",
      email: "john@email.com",
      phone: "8978675645",
      role: "Super User",
      type: "Admin",
      status: "Inactive",
      avatar:
        "https://www.rti.org/sites/default/files/styles/rti_1020x858/public/expert-images/051421_brian_southwell_profile-square_510.jpg?itok=4p6W3k1o",
    },
    {
      id: "4",
      firstName: "Charlie ",
      lastName: "Joe",
      lastLogin: "20 Dec 2022 at 02:25PM",
      email: "john@email.com",
      phone: "8978675645",
      role: "User",
      type: "Admin",
      status: "Inactive",
      avatar:
        "https://www.rti.org/sites/default/files/styles/rti_1020x858/public/expert-images/051421_brian_southwell_profile-square_510.jpg?itok=4p6W3k1o",
    },
    {
      id: "5",
      firstName: "Varun ",
      lastName: "Dhawan",
      lastLogin: "20 Dec 2022 at 02:25PM",
      email: "john@email.com",
      phone: "8978675645",
      role: "Admin",
      type: "Admin",
      status: "Inactive",
      avatar:
        "https://media.licdn.com/dms/image/C5603AQE87VJ7eUP7iQ/profile-displayphoto-shrink_800_800/0/1516272130754?e=2147483647&v=beta&t=7WnQqjq697rEJwraSF1nbJXOwm-nMUbs5s1lrpjniRg",
    },
    {
      id: "6",
      firstName: "Pranali ",
      lastName: "Joshi",
      lastLogin: "20 Dec 2022 at 02:25PM",
      email: "john@email.com",
      phone: "8978675645",
      role: "Staff",
      type: "Admin",
      status: "Pending",
      avatar:
        "https://www.rti.org/sites/default/files/styles/rti_1020x858/public/expert-images/051421_brian_southwell_profile-square_510.jpg?itok=4p6W3k1o",
    },
    {
      id: "7",
      firstName: "Thinkitive ",
      lastName: "Technologies",
      lastLogin: "20 Dec 2022 at 02:25PM",
      email: "john@email.com",
      phone: "8978675645",
      role: "Super User",
      type: "Admin",
      status: "Pending",
      avatar:
        "https://images.crunchbase.com/image/upload/c_lpad,f_auto,q_auto:eco,dpr_1/wwivurcw1hdgztzrkunz",
    },
    {
      id: "8",
      firstName: "Krishnali ",
      lastName: "Danot",
      lastLogin: "20 Dec 2022 at 02:25PM",
      email: "john@email.com",
      phone: "8978675645",
      role: "Super User",
      type: "Admin",
      status: "Active",
      avatar:
        "https://profilemagazine.com/wp-content/uploads/2020/04/Ajmere-Dale-Square-thumbnail.jpg",
    },
    {
      id: "9",
      firstName: "Krishnali ",
      lastName: "Danot",
      lastLogin: "20 Dec 2022 at 02:25PM",
      email: "john@email.com",
      phone: "8978675645",
      role: "Super User",
      type: "Admin",
      status: "Active",
      avatar:
        "https://www.rd.com/wp-content/uploads/2017/09/01-shutterstock_476340928-Irina-Bg.jpg",
    },
    {
      id: "10",
      firstName: "Krishnali ",
      lastName: "Danot",
      lastLogin: "20 Dec 2022 at 02:25PM",
      email: "john@email.com",
      phone: "8978675645",
      role: "Super User",
      type: "Admin",
      status: "Active",
      avatar:
        "https://assets.mobileworldlive.com/wp-content/uploads/2015/10/16130048/Dorsey-iamge.png",
    },
    {
      id: "10",
      firstName: "Krishnali ",
      lastName: "Danot",
      lastLogin: "20 Dec 2022 at 02:25PM",
      email: "john@email.com",
      phone: "8978675645",
      role: "Super User",
      type: "Admin",
      status: "Active",
      avatar:
        "https://assets.mobileworldlive.com/wp-content/uploads/2015/10/16130048/Dorsey-iamge.png",
    },
    {
      id: "10",
      firstName: "Krishnali ",
      lastName: "Danot",
      lastLogin: "20 Dec 2022 at 02:25PM",
      email: "john@email.com",
      phone: "8978675645",
      role: "Super User",
      type: "Admin",
      status: "Active",
      avatar:
        "https://assets.mobileworldlive.com/wp-content/uploads/2015/10/16130048/Dorsey-iamge.png",
    },
    {
      id: "10",
      firstName: "Krishnali ",
      lastName: "Danot",
      lastLogin: "20 Dec 2022 at 02:25PM",
      email: "john@email.com",
      phone: "8978675645",
      role: "Super User",
      type: "Admin",
      status: "Active",
      avatar:
        "https://assets.mobileworldlive.com/wp-content/uploads/2015/10/16130048/Dorsey-iamge.png",
    },
    {
      id: "10",
      firstName: "Krishnali ",
      lastName: "Danot",
      lastLogin: "20 Dec 2022 at 02:25PM",
      email: "john@email.com",
      phone: "8978675645",
      role: "Super User",
      type: "Admin",
      status: "Active",
      avatar:
        "https://assets.mobileworldlive.com/wp-content/uploads/2015/10/16130048/Dorsey-iamge.png",
    },
    {
      id: "10",
      firstName: "Krishnali ",
      lastName: "Danot",
      lastLogin: "20 Dec 2022 at 02:25PM",
      email: "john@email.com",
      phone: "8978675645",
      role: "Super User",
      type: "Admin",
      status: "Active",
      avatar:
        "https://assets.mobileworldlive.com/wp-content/uploads/2015/10/16130048/Dorsey-iamge.png",
    },
    {
      id: "10",
      firstName: "Krishnali ",
      lastName: "Danot",
      lastLogin: "20 Dec 2022 at 02:25PM",
      email: "john@email.com",
      phone: "8978675645",
      role: "Super User",
      type: "Admin",
      status: "Active",
      avatar:
        "https://assets.mobileworldlive.com/wp-content/uploads/2015/10/16130048/Dorsey-iamge.png",
    }
  ],
};

export const providerGroupsList = {
  content: [
    {
      groupID: "2358",
      groupName: "Jupiter Hospital",
      providers: "476",
      patients: "488",
      appointments: "654",
      encounters: "786",
    },
    {
      groupID: "3265",
      groupName: "Life Point Multispecialty",
      providers: "234",
      patients: "345",
      appointments: "357",
      encounters: "856",
    },
    {
      groupID: "1243",
      groupName: "Shalby Hospital",
      providers: "577",
      patients: "488",
      appointments: "776",
      encounters: "789",
    },
    {
      groupID: "2358",
      groupName: "Jupiter Hospital",
      providers: "476",
      patients: "488",
      appointments: "654",
      encounters: "786",
    },
    {
      groupID: "3265",
      groupName: "Life Point Multispecialty",
      providers: "234",
      patients: "345",
      appointments: "357",
      encounters: "856",
    },
    {
      groupID: "1243",
      groupName: "Shalby Hospital",
      providers: "577",
      patients: "488",
      appointments: "776",
      encounters: "789",
    },
    {
      groupID: "2358",
      groupName: "Jupiter Hospital",
      providers: "476",
      patients: "488",
      appointments: "654",
      encounters: "786",
    },
    {
      groupID: "3265",
      groupName: "Life Point Multispecialty",
      providers: "234",
      patients: "345",
      appointments: "357",
      encounters: "856",
    },
    {
      groupID: "3266",
      groupName: "Multispecialty",
      providers: "676",
      patients: "345",
      appointments: "358",
      encounters: "856",
    },
    {
      groupID: "3266",
      groupName: "Multispecialty",
      providers: "676",
      patients: "345",
      appointments: "358",
      encounters: "856",
    }
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 9,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};

export const dataImport = {
  content: [
    {
      id: "1",
      entity: "Patient Data",
      lastUpdatedDate: "19-04-2020",
      totalRecords: "25",
    },
    {
      id: "2",
      entity: "Provider Data",
      lastUpdatedDate: "25-02-2020",
      totalRecords: "13",
    },
    {
      id: "3",
      entity: "LOINC Code Catalog",
      lastUpdatedDate: "05-04-2022",
      totalRecords: "132",
    },
    {
      id: "4",
      entity: "Drug Catalog",
      lastUpdatedDate: "27-03-2022",
      totalRecords: "741",
    },
    {
      id: "5",
      entity: "ICD 10 Code Catalog",
      lastUpdatedDate: "25-02-2020",
      totalRecords: "153",
    },
    {
      id: "6",
      entity: "Patient Data",
      lastUpdatedDate: "19-04-2020",
      totalRecords: "25",
    },
    {
      id: "7",
      entity: "Provider Data",
      lastUpdatedDate: "25-02-2020",
      totalRecords: "13",
    },
    {
      id: "8",
      entity: "LOINC Code Catalog",
      lastUpdatedDate: "05-04-2022",
      totalRecords: "132",
    },
    {
      id: "9",
      entity: "Drug Catalog",
      lastUpdatedDate: "27-03-2022",
      totalRecords: "741",
    },
    {
      id: "10",
      entity: "ICD 10 Code Catalog",
      lastUpdatedDate: "25-02-2020",
      totalRecords: "153",
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 5,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};

export const loincData = {
  content: [
    {
      code: "100120",
      description:
        "6-oxo-piperidine-2-carboxylate & 6(R+S)-oxo-propylpiperidine-2-carboxylate panel",
      status: true,
    },
    {
      code: "27410",
      description: "Health informatics pioneer and cofounder of LOINC",
      status: true,
    },
    {
      code: "363541",
      description: "6(R+S)-oxo-propylpiperidine-2-carboxylate/Creatinine",
      status: false,
    },{
      code: "100120",
      description:
        "6-oxo-piperidine-2-carboxylate & 6(R+S)-oxo-propylpiperidine-2-carboxylate panel",
      status: true,
    },
    {
      code: "27410",
      description: "Health informatics pioneer and cofounder of LOINC",
      status: true,
    },
    {
      code: "363541",
      description: "6(R+S)-oxo-propylpiperidine-2-carboxylate/Creatinine",
      status: false,
    },{
      code: "100120",
      description:
        "6-oxo-piperidine-2-carboxylate & 6(R+S)-oxo-propylpiperidine-2-carboxylate panel",
      status: true,
    },
    {
      code: "27410",
      description: "Health informatics pioneer and cofounder of LOINC",
      status: true,
    },
    {
      code: "363541",
      description: "6(R+S)-oxo-propylpiperidine-2-carboxylate/Creatinine",
      status: false,
    },{
      code: "100120",
      description:
        "6-oxo-piperidine-2-carboxylate & 6(R+S)-oxo-propylpiperidine-2-carboxylate panel",
      status: true,
    },
    {
      code: "27410",
      description: "Health informatics pioneer and cofounder of LOINC",
      status: true,
    },
    {
      code: "363541",
      description: "6(R+S)-oxo-propylpiperidine-2-carboxylate/Creatinine",
      status: false,
    },{
      code: "100120",
      description:
        "6-oxo-piperidine-2-carboxylate & 6(R+S)-oxo-propylpiperidine-2-carboxylate panel",
      status: true,
    },
    {
      code: "27410",
      description: "Health informatics pioneer and cofounder of LOINC",
      status: true,
    },
    {
      code: "363541",
      description: "6(R+S)-oxo-propylpiperidine-2-carboxylate/Creatinine",
      status: false,
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};

export const icd10CodeData = {
  content: [
    {
      code: "A000",
      description: "Cholera due to Vibrio cholerae 01, biovar cholerae",
      status: true,
    },
    {
      code: "A245",
      description:
        "Enterocolitis due to Clostridium difficile, not specified as recurrent",
      status: true,
    },
    {
      code: "B456",
      description:
        "Whooping cough due to Bordetella parapertussis without pneumonia",
      status: false,
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};

export const cptCodeData = {
  content: [
    {
      code: "9685",
      description:
        "Psychological testing by a computer, including time for the psychologist’s interpretation and reporting",
      status: true,
    },
    {
      code: "6952",
      description:
        "Neuropsychological testing by a computer, including time for the psychologist’s interpretation and reporting",
      status: true,
    },
    {
      code: "7415",
      description:
        "Medical nutrition therapy; initial assessment & intervention, individual, face-to-face with the patient, each 15 minutes",
      status: false,
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};

export const hcpcsCodeData = {
  content: [
    {
      code: "9685",
      description:
        "Technetium tc 99m tilmanocept, diagnostic, up to 0.5 millicuries",
      status: true,
    },
    {
      code: "6952",
      description:
        "Laparoscopy, surgical, radiofrequency ablations of uterine fibroid(s), including intraoperative guidance and monitoring, when performed",
      status: true,
    },
    {
      code: "7415",
      description: "Tissue marker (implantable)",
      status: false,
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};

export const drugCatalogData = {
  content: [
    {
      id: "9685",
      speciality: "Physician",
      type: "TAB",
      medicine: "Pantoprazle",
      dose: "1-0-1",
      whenField: "After food",
      whereField: "On Scalp",
      frequency: "Twice a Day",
      duration: "2 Days",
      qty: "2",
      notesInstructions: "No",
      status: true,
    },
    {
      id: "6952",
      speciality: "Allergist",
      type: "TAB",
      medicine: "Pantoprazle",
      dose: "1-0-1",
      whenField: "After food",
      whereField: "",
      frequency: "Twice a Day",
      duration: "2 Days",
      qty: "2",
      notesInstructions: "No",
      status: true,
    },
    {
      id: "7415",
      speciality: "Physician",
      type: "TAB",
      medicine: "Pantoprazle",
      dose: "1-0-1",
      whenField: "After food",
      whereField: "",
      frequency: "Twice a Day",
      duration: "2 Days",
      qty: "2",
      notesInstructions: "No",
      status: false,
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};

export const auditLog = {
  date: "2023-08-08T11:51:36.672+00:00",
  code: "OK",
  message: "Audit log found successfully",
  data: [
    {
      id: 1,
      entity: "Patient",
      createdBy: "Kendal Luce",
      created: "2023-08-08",
      numberOfRecords: 1,
      providerGroupName: "Orchid2",
      status: true,
    },
    {
      id: 2,
      entity: "Patient",
      createdBy: "Kendal Luce",
      created: "2023-08-08",
      numberOfRecords: 61,
      providerGroupName: "Orchid2",
      status: false,
    },
    {
      id: 3,
      entity: "Patient",
      createdBy: "Cyrstal Dugger",
      created: "2023-08-08",
      numberOfRecords: 31,
      providerGroupName: "Orchid2",
      status: false,
    },
    {
      id: 4,
      entity: "Patient",
      createdBy: "Han Gann",
      created: "2023-08-08",
      numberOfRecords: 74,
      providerGroupName: "Orchid1",
      status: true,
    },
    {
      id: 5,
      entity: "Patient",
      createdBy: "Cyrstal Dugger",
      created: "2023-08-08",
      numberOfRecords: 56,
      providerGroupName: "Orchid1",
      status: false,
    },
    {
      id: 6,
      entity: "Patient",
      createdBy: "Kendal Luce",
      created: "2023-08-08",
      numberOfRecords: 20,
      providerGroupName: "Orchid1",
      status: false,
    },{
      id: 7,
      entity: "Patient",
      createdBy: "Cyrstal Dugger",
      created: "2023-08-08",
      numberOfRecords: 31,
      providerGroupName: "Orchid2",
      status: false,
    },
    {
      id: 8,
      entity: "Patient",
      createdBy: "Han Gann",
      created: "2023-08-08",
      numberOfRecords: 74,
      providerGroupName: "Orchid1",
      status: true,
    },
    {
      id: 9,
      entity: "Patient",
      createdBy: "Cyrstal Dugger",
      created: "2023-08-08",
      numberOfRecords: 56,
      providerGroupName: "Orchid1",
      status: false,
    },
    {
      id: 10,
      entity: "Patient",
      createdBy: "Kendal Luce",
      created: "2023-08-08",
      numberOfRecords: 20,
      providerGroupName: "Orchid1",
      status: false,
    },
    {
      id: 11,
      entity: "Patient",
      createdBy: "Cyrstal Dugger",
      created: "2023-08-08",
      numberOfRecords: 56,
      providerGroupName: "Orchid1",
      status: false,
    }
  ],
  path: "/api/admin/migration/audit-log/PROVIDER_DATA",
  requestId: "e2c3d6ec-6afc-4a6a-aaaf-26a530948af1",
  version: "1.0",
};

export const patientrecord = {
  date: "2023-08-08T11:51:36.672+00:00",
  code: "OK",
  message: "Audit log found successfully",
  data: [
    {
      id: 1,
      patientID: "526",
      patientName: "Cyrstal Dugger",
      // providerGroupName: "Global Hoapital",
      providerNames: "Tracee Bundy",
    },
    {
      id: 2,
      patientID: "41",
      patientName: "Chasity Cary",
      // providerGroupName: "Kendal Luce",
      providerNames: "Tracee Bundy",
    },
    {
      id: 3,
      patientID: "54",
      patientName: "Cyrstal Dugger",
      // providerGroupName: "Augustine Angel",
      providerNames: "Tracee Bundy",
    },
    {
      id: 4,
      patientID: "654",
      patientName: "Cyrstal Dugger",
      // providerGroupName: "Billroth Hospital",
      providerNames: "Tracee Bundy",
    },
    {
      id: 5,
      patientID: "145",
      patientName: "Penni Fitch",
      // providerGroupName: "Billroth Hospital",
      providerNames: "Tracee Bundy",
    },
    {
      id: 6,
      patientID: "7417",
      patientName: "Penni Fitch",
      // providerGroupName: "Kendal Luce",
      providerNames: "Tracee Bundy",
    },{
      id: 7,
      patientID: "54",
      patientName: "Cyrstal Dugger",
      // providerGroupName: "Augustine Angel",
      providerNames: "Tracee Bundy",
    },
    {
      id: 8,
      patientID: "654",
      patientName: "Cyrstal Dugger",
      // providerGroupName: "Billroth Hospital",
      providerNames: "Tracee Bundy",
    },
    {
      id: 9,
      patientID: "145",
      patientName: "Penni Fitch",
      // providerGroupName: "Billroth Hospital",
      providerNames: "Tracee Bundy",
    },
    {
      id: 10,
      patientID: "7417",
      patientName: "Penni Fitch",
      // providerGroupName: "Kendal Luce",
      providerNames: "Tracee Bundy",
    },
    {
      id: 11,
      patientID: "145",
      patientName: "Penni Fitch",
      // providerGroupName: "Billroth Hospital",
      providerNames: "Tracee Bundy",
    }
  ],
  path: "/api/admin/migration/audit-log/PROVIDER_DATA",
  requestId: "e2c3d6ec-6afc-4a6a-aaaf-26a530948af1",
  version: "1.0",
};

export const adminPatientrecord = {
  date: "2023-08-08T11:51:36.672+00:00",
  code: "OK",
  message: "Audit log found successfully",
  data: [
    {
      id: 1,
      // patientID: "526",
      patientName: "Cyrstal Dugger",
      providerGroupName: "Global Hoapital",
      providerNames: "Tracee Bundy",
      status:true
    },
    {
      id: 2,
      // patientID: "41",
      patientName: "Chasity Cary",
      providerGroupName: "Kendal Luce",
      providerNames: "Tracee Bundy",
      status:true
    },
    {
      id: 3,
      // patientID: "54",
      patientName: "Cyrstal Dugger",
      providerGroupName: "Augustine Angel",
      providerNames: "Tracee Bundy",
      status:false
    },
    {
      id: 4,
      // patientID: "654",
      patientName: "Cyrstal Dugger",
      providerGroupName: "Billroth Hospital",
      providerNames: "Tracee Bundy",
      status:false
    },
    {
      id: 5,
      // patientID: "145",
      patientName: "Penni Fitch",
      providerGroupName: "Billroth Hospital",
      providerNames: "Tracee Bundy",
      status:false
    },
    {
      id: 6,
      // patientID: "7417",
      patientName: "Penni Fitch",
      providerGroupName: "Kendal Luce",
      providerNames: "Tracee Bundy",
      status:true
    },{
      id: 7,
      // patientID: "54",
      patientName: "Cyrstal Dugger",
      providerGroupName: "Augustine Angel",
      providerNames: "Tracee Bundy",
      status:false
    },
    {
      id: 8,
      // patientID: "654",
      patientName: "Cyrstal Dugger",
      providerGroupName: "Billroth Hospital",
      providerNames: "Tracee Bundy",
      status:true
    },
    {
      id: 9,
      // patientID: "145",
      patientName: "Penni Fitch",
      providerGroupName: "Billroth Hospital",
      providerNames: "Tracee Bundy",
      status:false
    },
    {
      id: 10,
      // patientID: "7417",
      patientName: "Penni Fitch",
      providerGroupName: "Kendal Luce",
      providerNames: "Tracee Bundy",
    },
    {
      id: 11,
      // patientID: "145",
      patientName: "Penni Fitch",
      providerGroupName: "Billroth Hospital",
      providerNames: "Tracee Bundy",
      status:false
    }
  ],
  path: "/api/admin/migration/audit-log/PROVIDER_DATA",
  requestId: "e2c3d6ec-6afc-4a6a-aaaf-26a530948af1",
  version: "1.0",
};

export const todaysAppointment = {
  content: [
    {
      time: "10:30 AM - 11:00 AM",
      duration: "30 Mins",
      patientName: "Henna West (A242)",
      age: "65 yrs",
      mobileno: "(235) 143-3243",
      provider: "Dr. Corina",
      speciality: "Dermatology",
      location: "Location 1",
      appointmentType: "New Appointment",
      reasonForVisit: "Cough & Fever",
      action: "Schedule",
    },
    {
      time: "10:30 AM - 11:00 AM",
      duration: "30 Mins",
      patientName: "Henna West (A242)",
      age: "65 yrs",
      mobileno: "(235) 143-3243",
      provider: "Dr. Corina",
      speciality: "Dermatology",
      location: "Location 1",
      appointmentType: "New Appointment",
      reasonForVisit: "Cough & Fever",
      action: "Schedule",
    },
    {
      time: "10:30 AM - 11:00 AM",
      duration: "30 Mins",
      patientName: "Henna West (A242)",
      age: "65 yrs",
      mobileno: "(235) 143-3243",
      provider: "Dr. Corina",
      speciality: "Dermatology",
      location: "Location 1",
      appointmentType: "New Appointment",
      reasonForVisit: "Infection Disease",
      action: "Check In",
    },
    {
      time: "10:30 AM - 11:00 AM",
      duration: "30 Mins",
      patientName: "Henna West (A242)",
      age: "65 yrs",
      mobileno: "(235) 143-3243",
      provider: "Dr. Corina",
      speciality: "Dermatology",
      location: "Location 1",
      appointmentType: "New Appointment",
      reasonForVisit: "Fever",
      action: "Exam Room",
    },
    {
      time: "10:30 AM - 11:00 AM",
      duration: "30 Mins",
      patientName: "Henna West (A242)",
      age: "65 yrs",
      mobileno: "(235) 143-3243",
      provider: "Dr. Corina",
      speciality: "Dermatology",
      location: "Location 1",
      appointmentType: "New Appointment",
      reasonForVisit: "Infection Disease",
      action: "Check In",
    },
    {
      time: "10:30 AM - 11:00 AM",
      duration: "30 Mins",
      patientName: "Henna West (A242)",
      age: "65 yrs",
      mobileno: "(235) 143-3243",
      provider: "Dr. Corina",
      speciality: "Dermatology",
      location: "Location 1",
      appointmentType: "New Appointment",
      reasonForVisit: "Cough & Fever",
      action: "Schedule",
    },
    {
      time: "10:30 AM - 11:00 AM",
      duration: "30 Mins",
      patientName: "Henna West (A242)",
      age: "65 yrs",
      mobileno: "(235) 143-3243",
      provider: "Dr. Corina",
      speciality: "Dermatology",
      location: "Location 1",
      appointmentType: "New Appointment",
      reasonForVisit: "Infection Disease",
      action: "Check In",
    },
    {
      time: "10:30 AM - 11:00 AM",
      duration: "30 Mins",
      patientName: "Henna West (A242)",
      age: "65 yrs",
      mobileno: "(235) 143-3243",
      provider: "Dr. Corina",
      speciality: "Dermatology",
      location: "Location 1",
      appointmentType: "New Appointment",
      reasonForVisit: "Infection Disease",
      action: "Check In",
    },
    {
      time: "10:30 AM - 11:00 AM",
      duration: "30 Mins",
      patientName: "Henna West (A242)",
      age: "65 yrs",
      mobileno: "(235) 143-3243",
      provider: "Dr. Corina",
      speciality: "Dermatology",
      location: "Location 1",
      appointmentType: "New Appointment",
      reasonForVisit: "Cough & Fever",
      action: "Schedule",
    },
    {
      time: "10:30 AM - 11:00 AM",
      duration: "30 Mins",
      patientName: "Henna West (A242)",
      age: "65 yrs",
      mobileno: "(235) 143-3243",
      provider: "Dr. Corina",
      speciality: "Dermatology",
      location: "Location 1",
      appointmentType: "New Appointment",
      reasonForVisit: "Infection Disease",
      action: "Check In",
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};

export const unsignedEncounter = {
  content: [
    {
      dateofService: "10-07-2022",
      patientName: "Henna West (A242)",
      age: "65 yrs",
      mobileno: "(235) 143-3243",
      provider: "Dr. Corina",
      speciality: "Dermatology",
      location: "Location 1",
      action: "Awaiting of sign-off",
    },
    {
      dateofService: "01-06-2022",
      patientName: "Henna West (A242)",
      age: "65 yrs",
      mobileno: "(235) 143-3243",
      provider: "Dr. Corina",
      speciality: "Dermatology",
      location: "Location 1",
      action: "Missing CPT code",
    },
    {
      dateofService: "01-06-2022",
      patientName: "Henna West (A242)",
      age: "65 yrs",
      mobileno: "(235) 143-3243",
      provider: "Dr. Corina",
      speciality: "Dermatology",
      location: "Location 1",
      action: "Awaiting of sign-off",
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};

export const newLabReports = {
  content: [
    {
      testName: "X-ray",
      patientName: "Henna West",
      uplodatedDate: "10-07-2022",
    },
    {
      testName: "kidney functio…",
      patientName: "Henna West",
      uplodatedDate: "22-05-2022",
    },
    {
      testName: "01-06-2022",
      patientName: "Henna West",
      uplodatedDate: "22-05-2022",
    },
    {
      testName: "X-ray",
      patientName: "Henna West",
      uplodatedDate: "10-07-2022",
    },
    {
      testName: "kidney functio…",
      patientName: "Henna West",
      uplodatedDate: "22-05-2022",
    },
    {
      testName: "01-06-2022",
      patientName: "Henna West",
      uplodatedDate: "22-05-2022",
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};

export const recentlyAddedPatients = {
  content: [
    {
      patientName: "Cooper Franci (A3421)",
      age: "65 yrs",
      dob: "23-06-1975",
      date: "14-05-2022",
    },
    {
      patientName: "Hanna Westervelt (A2437)",
      age: "65 yrs",
      dob: "23-06-1975",
      date: "08-05-2022",
    },
    {
      patientName: "Jocelyn Vetrovs (A4753)",
      age: "56 yrs",
      dob: "23-06-1975",
      date: "05-05-2022",
    },
    {
      patientName: "Aaron Brown (A4253)",
      age: "37 yrs",
      dob: "23-06-1975",
      date: "14-05-2022",
    },
    {
      patientName: "Henna West (A242)",
      age: "65 yrs",
      dob: "23-06-1975",
      date: "14-05-2022",
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};

export const providerAdminData = {
  content: [
    {
      id: "A7892",
      legalFirstName: "Kiran",
      legalLastName: "Rathod",
      provider: {
        firstName: "Dr.Geller",
        lastName: "Para",
      },
      location: {
        id: 1,
        uuid: "ed9717b0-173f-44b1-99b1-eb83da8006cc",
        locationId: "78",
        name: "Jeet health care",
        specialities: [
          {
            id: 1,
            name: "Cardiology",
          },
        ],
      },
      npiNumber: "34567898",
      contactNumber: "9966558899",
      email: "indra@valid.com",
      yearOfExperience: "5",
      totalPatients: "796",
      status: false,
    },
    {
      id: "A3645",
      uuid: "e942145b-d46e-4999-8193-545c98c65621",
      provider: {
        firstName: "Dr. Corina",
        lastName: "Para",
      },
      location: {
        id: 1,
        uuid: "ed9717b0-173f-44b1-99b1-eb83da8006cc",
        locationId: "78",
        name: "Jeet health care",
        specialities: [
          {
            id: 1,
            name: "Neurology",
          },
        ],
        contactNumber: "9915078221",
        active: true,
        addressCheckBox: false,
      },
      providerGroupId: "5dbc72c0-c598-45dc-85b5-2e08b3a8db08",
      legalLastName: "Para",
      legalFirstName: "Corina",
      birthDate: "2011-05-01T00:00:00Z",
      contactNumber: "(569) 822-4144",
      email: "hennawest@gmail.com",
      yearOfExperience: "4",
      npiNumber: "451274855",
      totalPatients: "963",
      status: false,
    },
    {
      id: "A8456",
      uuid: "e942145b-d46e-4999-8193-545c98c65621",
      provider: {
        firstName: "Gina ",
        lastName: "Tribbiani",
      },
      location: {
        id: 1,
        uuid: "ed9717b0-173f-44b1-99b1-eb83da8006cc",
        locationId: "78",
        name: "Jeet health care",
        specialities: [
          {
            id: 1,
            name: "Cardiology",
          },
        ],
        contactNumber: "9966558899",
        active: true,
        addressCheckBox: false,
      },
      providerGroupId: "5dbc72c0-c598-45dc-85b5-2e08b3a8db08",
      registrationDate: "2022-01-01T12:00:00Z",
      legalLastName: "Bhosle",
      legalFirstName: "Neha",
      birthDate: "2011-05-01T00:00:00Z",

      contactNumber: "4465766572",
      email: "maryriddle@outlook.com",

      yearOfExperience: "11",
      npiNumber: "7418529645",
      totalPatients: "78",
      status: false,
    },
    {
      id: "A7812",
      uuid: "e942145b-d46e-4999-8193-545c98c65621",
      provider: {
        firstName: "Chandler",
        lastName: "Bing",
      },
      location: {
        id: 1,
        uuid: "ed9717b0-173f-44b1-99b1-eb83da8006cc",
        locationId: "78",
        name: "Jeet health care",
        specialities: [
          {
            id: 1,
            name: "Cardiology",
          },
        ],
        contactNumber: "9966558899",
        active: true,
        addressCheckBox: false,
      },
      providerGroupId: "5dbc72c0-c598-45dc-85b5-2e08b3a8db08",
      registrationDate: "2022-01-01T12:00:00Z",
      legalLastName: "Chandler",
      legalFirstName: "Bing",
      birthDate: "2011-05-01T00:00:00Z",

      contactNumber: "(569) 822-4144",
      email: "ronweasley@outlook.com",

      yearOfExperience: "1",
      npiNumber: "34567898",
      totalPatients: "26",
      status: false,
    },
    {
      id: "A4568",
      uuid: "e942145b-d46e-4999-8193-545c98c65621",
      provider: {
        firstName: "Edward",
        lastName: "Smith",
      },
      location: {
        id: 1,
        uuid: "ed9717b0-173f-44b1-99b1-eb83da8006cc",
        locationId: "78",
        name: "Jeet health care",
        specialities: [
          {
            id: 1,
            name: "Gastroenterology",
          },
        ],
        contactNumber: "4795786779",
        active: true,
        addressCheckBox: false,
      },
      providerGroupId: "5dbc72c0-c598-45dc-85b5-2e08b3a8db08",
      registrationDate: "2022-01-01T12:00:00Z",
      legalLastName: "Edward ",
      legalFirstName: "Smith",
      birthDate: "2011-05-01T00:00:00Z",

      contactNumber: "5550034567",
      email: "neha@mailinator.com",

      yearOfExperience: "5",
      npiNumber: "34567898",
      totalPatients: "796",
      status: false,
    },
    {
      id: "A56820",
      uuid: "e942145b-d46e-4999-8193-545c98c65621",
      provider: {
        firstName: "Dr.Geller",
        lastName: "Para",
      },
      location: {
        id: 1,
        uuid: "ed9717b0-173f-44b1-99b1-eb83da8006cc",
        locationId: "78",
        name: "Jeet health care",
        specialities: [
          {
            id: 1,
            name: "Cardiology",
          },
        ],
        contactNumber: "9966558899",
        active: true,
        addressCheckBox: false,
      },
      providerGroupId: "5dbc72c0-c598-45dc-85b5-2e08b3a8db08",
      registrationDate: "2022-01-01T12:00:00Z",
      legalLastName: "Bhosle",
      legalFirstName: "Neha",
      birthDate: "2011-05-01T00:00:00Z",

      contactNumber: "5550034567",
      email: "neha@mailinator.com",

      yearOfExperience: "5",
      npiNumber: "34567898",
      totalPatients: "796",
      status: false,
    },
    {
      id: "A9656",
      uuid: "e942145b-d46e-4999-8193-545c98c65621",
      provider: {
        firstName: "Dr.Geller",
        lastName: "Para",
      },
      location: {
        id: 1,
        uuid: "ed9717b0-173f-44b1-99b1-eb83da8006cc",
        locationId: "78",
        name: "Jeet health care",
        specialities: [
          {
            id: 1,
            name: "Cardiology",
          },
        ],
        contactNumber: "9966558899",
        active: true,
        addressCheckBox: false,
      },
      providerGroupId: "5dbc72c0-c598-45dc-85b5-2e08b3a8db08",
      registrationDate: "2022-01-01T12:00:00Z",
      legalLastName: "Bhosle",
      legalFirstName: "Neha",
      birthDate: "2011-05-01T00:00:00Z",

      contactNumber: "5550034567",
      email: "neha@mailinator.com",

      yearOfExperience: "5",
      npiNumber: "34567898",
      totalPatients: "796",
      status: false,
    },
    {
      id: "A5666",
      uuid: "e942145b-d46e-4999-8193-545c98c65621",
      provider: {
        firstName: "Dr.Geller",
        lastName: "Para",
      },
      location: {
        id: 1,
        uuid: "ed9717b0-173f-44b1-99b1-eb83da8006cc",
        locationId: "78",
        name: "Jeet health care",
        specialities: [
          {
            id: 1,
            name: "Cardiology",
          },
        ],
        contactNumber: "9966558899",
        active: true,
        addressCheckBox: false,
      },
      providerGroupId: "5dbc72c0-c598-45dc-85b5-2e08b3a8db08",
      registrationDate: "2022-01-01T12:00:00Z",
      legalLastName: "Bhosle",
      legalFirstName: "Neha",
      birthDate: "2011-05-01T00:00:00Z",

      contactNumber: "5550034567",
      email: "neha@mailinator.com",

      yearOfExperience: "5",
      npiNumber: "34567898",
      totalPatients: "796",
      status: false,
    },
    {
      id: "A5456",
      uuid: "e942145b-d46e-4999-8193-545c98c65621",
      provider: {
        firstName: "Dr.Geller",
        lastName: "Para",
      },
      location: {
        id: 1,
        uuid: "ed9717b0-173f-44b1-99b1-eb83da8006cc",
        locationId: "78",
        name: "Jeet health care",
        specialities: [
          {
            id: 1,
            name: "Cardiology",
          },
        ],
        contactNumber: "9966558899",
        active: true,
        addressCheckBox: false,
      },
      providerGroupId: "5dbc72c0-c598-45dc-85b5-2e08b3a8db08",
      registrationDate: "2022-01-01T12:00:00Z",
      legalLastName: "Bhosle",
      legalFirstName: "Neha",
      birthDate: "2011-05-01T00:00:00Z",

      contactNumber: "5550034567",
      email: "neha@mailinator.com",

      yearOfExperience: "5",
      npiNumber: "34567898",
      totalPatients: "796",
      status: false,
    },
    {
      id: "A2302",
      uuid: "e942145b-d46e-4999-8193-545c98c65621",
      provider: {
        firstName: "Dr.Geller",
        lastName: "Para",
      },
      location: {
        id: 1,
        uuid: "ed9717b0-173f-44b1-99b1-eb83da8006cc",
        locationId: "78",
        name: "Jeet health care",
        specialities: [
          {
            id: 1,
            name: "Cardiology",
          },
        ],
        contactNumber: "9966558899",
        active: true,
        addressCheckBox: false,
      },
      providerGroupId: "5dbc72c0-c598-45dc-85b5-2e08b3a8db08",
      registrationDate: "2022-01-01T12:00:00Z",
      legalLastName: "Bhosle",
      legalFirstName: "Neha",
      birthDate: "2011-05-01T00:00:00Z",

      contactNumber: "5550034567",
      email: "neha@mailinator.com",

      yearOfExperience: "5",
      npiNumber: "34567898",
      totalPatients: "796",
      status: false,
    },
    {
      id: "A40036",
      uuid: "e942145b-d46e-4999-8193-545c98c65621",
      provider: {
        firstName: "Dr.Geller",
        lastName: "Para",
      },
      location: {
        id: 1,
        uuid: "ed9717b0-173f-44b1-99b1-eb83da8006cc",
        locationId: "78",
        name: "Jeet health care",
        specialities: [
          {
            id: 1,
            name: "Cardiology",
          },
        ],
        contactNumber: "9966558899",
        active: true,
        addressCheckBox: false,
      },
      providerGroupId: "5dbc72c0-c598-45dc-85b5-2e08b3a8db08",
      registrationDate: "2022-01-01T12:00:00Z",
      legalLastName: "Bhosle",
      legalFirstName: "Neha",
      birthDate: "2011-05-01T00:00:00Z",

      contactNumber: "5550034567",
      email: "neha@mailinator.com",

      yearOfExperience: "5",
      npiNumber: "34567898",
      totalPatients: "796",
      status: false,
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};
