export const allergiesforms = {
  content: [
    {
      allergies: "Cigarette smoke",
      criticality: "High",
      reason: "Cough",
      severity: "Mild",
      onsetdate: "04-10-2022",
      updateddate: "04-10-2022",
      status: false,
      note: "Patient has allergies",
      action: true,
    },
    {
      allergies: "Milk",
      criticality: "Low",
      reason: "Vomit",
      severity: "Moderate",
      onsetdate: "10-10-2022",
      updateddate: "04-10-2022",
      status: true,
      note: "Patient has allergies",
      action: true,
    },
    {
      allergies: "Dust",
      criticality: "High",
      reason: "Tightness In Breathing",
      severity: "Severity",
      onsetdate: "15-10-2022",
      updateddate: "04-10-2022",
      status: false,
      note: "Patient has allergies",
      action: true,
    },
    {
      allergies: "Cigarette smoke",
      criticality: "High",
      reason: "Cough",
      severity: "Mild",
      onsetdate: "04-10-2022",
      updateddate: "04-10-2022",
      status: true,
      note: "Patient has allergies",
      action: true,
    },
    {
      allergies: "Milk",
      criticality: "Low",
      reason: "Vomit",
      severity: "Moderate",
      onsetdate: "10-10-2022",
      updateddate: "04-10-2022",
      status: true,
      note: "Patient has allergies",
      action: true,
    },
    {
      allergies: "Dust",
      criticality: "High",
      reason: "Tightness In Breathing",
      severity: "Severity",
      onsetdate: "15-10-2022",
      updateddate: "04-10-2022",
      status: false,
      note: "Patient has allergies",
      action: true,
    },
    {
      allergies: "Milk",
      criticality: "Low",
      reason: "Vomit",
      severity: "Moderate",
      onsetdate: "10-10-2022",
      updateddate: "04-10-2022",
      status: true,
      note: "Patient has allergies",
      action: true,
    },
    {
      allergies: "Dust",
      criticality: "High",
      reason: "Tightness In Breathing",
      severity: "Severity",
      onsetdate: "15-10-2022",
      updateddate: "04-10-2022",
      status: false,
      note: "Patient has allergies",
      action: true,
    },
    {
      allergies: "Milk",
      criticality: "Low",
      reason: "Vomit",
      severity: "Moderate",
      onsetdate: "10-10-2022",
      updateddate: "04-10-2022",
      status: true,
      note: "Patient has allergies",
      action: true,
    },
    {
      allergies: "Dust",
      criticality: "High",
      reason: "Tightness In Breathing",
      severity: "Severity",
      onsetdate: "15-10-2022",
      updateddate: "04-10-2022",
      status: false,
      note: "Patient has allergies",
      action: true,
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};

export const patientallergiesdata = {
  content: [
    {
      allergies: "Cigarette smoke",
      provider: "Corina Smith",
      reaction: "Cough",
      note: "Patient has allergies",
    },
    {
      allergies: "Milk",
      provider: "Monica Geller",
      reaction: "Vomit",
      note: "Patient has allergies",
    },
    {
      allergies: "Dust",
      provider: "Gina Tribbiani",
      reaction: "Tightness In Breathing",
      note: "Patient has allergies",
    },
    {
      allergies: "Cigarette smoke",
      provider: "Corina Smith",
      reaction: "Cough",
      note: "Patient has allergies",
    },
    {
      allergies: "Milk",
      provider: "Monica Geller",
      reaction: "Vomit",
      note: "Patient has allergies",
    },
    {
      allergies: "Dust",
      provider: "Gina Tribbiani",
      reaction: "Tightness In Breathing",
      note: "Patient has allergies",
    },
    {
      allergies: "Cigarette smoke",
      provider: "Corina Smith",
      reaction: "Cough",
      note: "Patient has allergies",
    },
    {
      allergies: "Milk",
      provider: "Monica Geller",
      reaction: "Vomit",
      note: "Patient has allergies",
    },
    {
      allergies: "Dust",
      provider: "Gina Tribbiani",
      reaction: "Tightness In Breathing",
      note: "Patient has allergies",
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};
