import patientImage from "../assets/other/patientImage.png";
// import DemelzaRobins from "../../assets/other/demelzaRobins.png";
// import MaryRiddle from "../../assets/other/maryRiddle.png";
// import LudoBagman from "../../assets/other/ludoBagman.png";
export const futureappointmentsdata = {
  content: [
    {
      scheduletime: "Fri Mar 21, 2022",
      time: "04:20 PM",
      speciality: "Obesity",
      provider: "Dr. Corina",
      reason: "Skin Infection",
      location: "Location 1",
      appointmenttype: "New Appointment",
      appointmentstatus: "Confirmed",
      action: true,
    },
    {
      scheduletime: "Fri Mar 21, 2022",
      time: "02:20 PM",
      provider: "Monica Geller",
      speciality: "Dermatology",
      reason: "Cough & Fever",
      location: "42743 Mule Ridge Rd Sardis, Ohio(OH), 43946",
      appointmenttype: "New Appointment",
      appointmentstatus: "Pending",
      action: true,
    },

    {
      scheduletime: "Fri Mar 21, 2022",
      provider: "Dr. Corina",
      time: "02:20 PM",
      speciality: "Neurology",
      reason: "Cough & Fever",
      location: "3414 Harrison Rd Castalia, North Carolina(NC), 27816",
      appointmenttype: "New Appointment",
      appointmentstatus: "Confirmed",
      action: true,
    },
    {
      scheduletime: "Fri Mar 21, 2022",
      provider: "Monica Geller",
      time: "03:20 PM",
      speciality: "Obesity",
      reason: "Cough & Fever",
      location: "42743 Mule Ridge Rd Sardis, Ohio(OH), 43946",
      appointmenttype: "New Appointment",
      appointmentstatus: "Pending",
      action: true,
    },
    {
      scheduletime: "Fri Mar 21, 2022",
      provider: "Dr. Corina",
      time: "01:20 PM",
      speciality: "Obesity",
      reason: "Skin Infection",
      location: "3414 Harrison Rd Castalia, North Carolina(NC), 27816",
      appointmenttype: "New Appointment",
      appointmentstatus: "Confirmed",
      action: true,
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};

export const pastappointmentsdata = {
  content: [
    {
      scheduletime: "Fri Mar 21, 2022",
      provider: "Dr. Corina",
      role: "Dermatology",
      time: "02:20 PM",
      speciality: "Obesity",
      reason: "Skin Infection",
      appointmenttype: "New Appointment",
      appointmentstatus: "Completed",
      billstatus: "Paid",
      action: true,
    },
    {
      scheduletime: "Fri Mar 21, 2022",
      provider: "Dr. Corina",
      time: "03:20 PM",
      speciality: "Obesity",
      role: "Dermatology",
      reason: "Infection Disease",
      appointmenttype: "New Appointment",
      appointmentstatus: "Cancel",
      billstatus: "Paid",
      action: true,
    },
    {
      scheduletime: "Fri Mar 21, 2022",
      provider: "Dr. Corina",
      role: "Dermatology",
      time: "02:20 PM",
      speciality: "Obesity",
      reason: "Cough & Fever",
      appointmenttype: "New Appointment",
      appointmentstatus: "Completed",
      billstatus: "Pending",
      action: true,
    },
    {
      scheduletime: "Fri Mar 21, 2022",
      provider: "Dr. Corina",
      time: "02:20 PM",
      speciality: "Obesity",
      role: "Dermatology",
      reason: "Skin Infection",
      appointmenttype: "New Appointment",
      appointmentstatus: "Completed",
      billstatus: "Paid",
      action: true,
    },
    {
      scheduletime: "Fri Mar 21, 2022",
      provider: "Dr. Corina",
      time: "04:30 PM",
      speciality: "Obesity",
      role: "Dermatology",
      reason: "Infection Disease",
      appointmenttype: "New Appointment",
      appointmentstatus: "Cancel",
      billstatus: "",
      action: true,
    },
    {
      scheduletime: "Fri Mar 21, 2022",
      provider: "Dr. Corina",
      time: "02:20 PM",
      speciality: "Obesity",
      role: "Dermatology",
      reason: "Cough & Fever",
      appointmenttype: "New Appointment",
      appointmentstatus: "Completed",
      billstatus: "Pending",
      action: true,
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};

export const patientMyAppointmentsData = {
  content: [
    {
      datetime: "Nov 12 2022",
      avatar: patientImage,
      time: "04:20 AM - 11:00 AM",
      speciality: "Dermatology",
      providername: "Henna West",
      reasonforvisit: "Sudden onset of high fever",
      locations: "Location 1",
      appointmenttype: "New Appointment",
      intakeformstatus: "Not Submitted",
      copay: "$ 20 Due",
      status: "Scheduled",
      action: true,
    },
    {
      datetime: "Sep 13 2021",
      avatar: patientImage,
      time: "11:30 AM - 12:00 PM",
      speciality: "Neurology",
      providername: "Monica Geller",
      reasonforvisit: "Headache, muscle aches and joint pain.",
      locations: "Location 2",
      appointmenttype: "Follow Up",
      intakeformstatus: "Submitted",
      copay: "$ 20 Due",
      status: "Completed",
      action: true,
    },
    {
      datetime: "Aug 10 2021",
      avatar: patientImage,
      time: "12:00 PM - 12:30 PM",
      speciality: "Dermatology",
      providername: "Chandler Bing",
      reasonforvisit: "Nasal congestion and runny nose.",
      locations: "Location 1",
      appointmenttype: "Follow Up",
      intakeformstatus: "Submitted",
      copay: "$ 20 Due",
      status: "Scheduled",
      action: true,
    },
    {
      datetime: "June 21 2021",
      avatar: patientImage,
      time: "01:00 PM - 02:00 PM",
      speciality: "Dermatology",
      providername: "Edward Smith",
      reasonforvisit: "Sudden onset of high fever",
      locations: "Location 1",
      appointmenttype: "Follow Up",
      intakeformstatus: "Not Submitted",
      copay: "$ 20 Due",
      status: "Cancelled",
      action: true,
    },
    {
      datetime: "Mar 02 2021",
      avatar: patientImage,
      time: "02:00 PM - 03:00 PM",
      speciality: "Dermatology",
      providername: "Gina Tribbiani",
      reasonforvisit: "Headache, muscle aches and joint pain.",
      locations: "Location 2",
      appointmenttype: "New Appointment",
      intakeformstatus: "",
      copay: "$ 20 Due",
      status: "Pending",
      action: true,
    },
    {
      datetime: "Nov 12 2022",
      avatar: patientImage,
      time: "04:20 AM - 11:00 AM",
      speciality: "Dermatology",
      providername: "Henna West",
      reasonforvisit: "Sudden onset of high fever",
      locations: "Location 1",
      appointmenttype: "New Appointment",
      intakeformstatus: "Not Submitted",
      copay: "$ 20 Due",
      status: "Scheduled",
      action: true,
    },
    {
      datetime: "Sep 13 2021",
      avatar: patientImage,
      time: "11:30 AM - 12:00 PM",
      speciality: "Neurology",
      providername: "Monica Geller",
      reasonforvisit: "Headache, muscle aches and joint pain.",
      locations: "Location 2",
      appointmenttype: "Follow Up",
      intakeformstatus: "Submitted",
      copay: "$ 20 Due",
      status: "Completed",
      action: true,
    },
    {
      datetime: "Aug 10 2021",
      avatar: patientImage,
      time: "12:00 PM - 12:30 PM",
      speciality: "Dermatology",
      providername: "Chandler Bing",
      reasonforvisit: "Nasal congestion and runny nose.",
      locations: "Location 1",
      appointmenttype: "Follow Up",
      intakeformstatus: "Submitted",
      copay: "$ 20 Due",
      status: "Scheduled",
      action: true,
    },
    {
      datetime: "June 21 2021",
      avatar: patientImage,
      time: "01:00 PM - 02:00 PM",
      speciality: "Dermatology",
      providername: "Edward Smith",
      reasonforvisit: "Sudden onset of high fever",
      locations: "Location 1",
      appointmenttype: "Follow Up",
      intakeformstatus: "Not Submitted",
      copay: "$ 20 Due",
      status: "Cancelled",
      action: true,
    },
    {
      datetime: "Mar 02 2021",
      avatar: patientImage,
      time: "02:00 PM - 03:00 PM",
      speciality: "Dermatology",
      providername: "Gina Tribbiani",
      reasonforvisit: "Headache, muscle aches and joint pain.",
      locations: "Location 2",
      appointmenttype: "New Appointment",
      intakeformstatus: "",
      copay: "$ 20 Due",
      status: "Pending",
      action: true,
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};

export const patientPastAppointmentsData = {
  content: [
    {
      scheduletime: "Fri Mar 21, 2022",
      avatar: patientImage,
      time: "04:20 AM",
      speciality: "Dermatology",
      providername: "Henna West",
      reason: "Skin Infection",
      appointmenttype: "New Appointment",
      appointmentstatus: "Completed",
      billstatus: "Paid",
      action: true,
    },
    {
      scheduletime: "Mon Mar 30, 2022",
      avatar: patientImage,
      time: "11:30 AM",
      speciality: "Neurology",
      providername: "Monica Geller",
      reason: "Cough & Fever",
      appointmenttype: "Follow Up",
      appointmentstatus: "Cancel",
      billstatus: "",
      action: true,
    },
    {
      scheduletime: "Thu Apri 15, 2022",
      avatar: patientImage,
      time: "12:00 PM",
      speciality: "Dermatology",
      providername: "Chandler Bing",
      reason: "Infection Disease",
      appointmenttype: "Follow Up",
      appointmentstatus: "Completed",
      billstatus: "Pending",
      action: true,
    },
    {
      scheduletime: "Fri Mar 21, 2022",
      avatar: patientImage,
      time: "04:20 AM",
      speciality: "Dermatology",
      providername: "Henna West",
      reason: "Skin Infection",
      appointmenttype: "New Appointment",
      appointmentstatus: "Completed",
      billstatus: "Paid",
      action: true,
    },
    {
      scheduletime: "Mon Mar 30, 2022",
      avatar: patientImage,
      time: "11:30 AM",
      speciality: "Neurology",
      providername: "Monica Geller",
      reason: "Cough & Fever",
      appointmenttype: "Follow Up",
      appointmentstatus: "Cancel",
      billstatus: "",
      action: true,
    },
    {
      scheduletime: "Thu Apri 15, 2022",
      avatar: patientImage,
      time: "12:00 PM",
      speciality: "Dermatology",
      providername: "Chandler Bing",
      reason: "Infection Disease",
      appointmenttype: "Follow Up",
      appointmentstatus: "Completed",
      billstatus: "Pending",
      action: true,
    },
    {
      scheduletime: "Fri Mar 21, 2022",
      avatar: patientImage,
      time: "04:20 AM",
      speciality: "Dermatology",
      providername: "Henna West",
      reason: "Skin Infection",
      appointmenttype: "New Appointment",
      appointmentstatus: "Completed",
      billstatus: "Paid",
      action: true,
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};
