export const authorizationdata = {
  content: [
    {
      authorization: "735574587",
      procedurecodes: "90846",
      startdate: "Mar 12 2022",
      enddate: "Jan 25 2025",
      speciality: "Obesity",
      visitapproved: "8",
      visitremaining: "4",
      notes: "Approved for 8 Visits",
      status: true,
    },

    {
      authorization: "424836598",
      procedurecodes: "90849",
      startdate: "Nov 12 2021",
      enddate: "Feb 10 2022",
      speciality: "Urgent Care",
      visitapproved: "7",
      visitremaining: "2",
      notes: "Approved for 8 Visits",
      status: false,
    },
    {
      authorization: "339342368",
      procedurecodes: "96111",
      startdate: "Nov 12 2023",
      enddate: "Nov 12 2028",
      speciality: "Dermatology",
      visitapproved: "6",
      visitremaining: "3",
      notes: "Approved for 6 Visits",
      status: true,
    },

    {
      authorization: "403914518",
      procedurecodes: "97770",
      startdate: "Nov 12 2021",
      enddate: "Nov 12 2021",
      speciality: "Cardiology",
      visitapproved: "5",
      visitremaining: "4",
      notes: "Approved for 5 Visits",
      status: false,
    },
    {
      authorization: "403914547",
      procedurecodes: "92522",
      startdate: "Sep 12 2023",
      enddate: "Nov 12 2029",
      speciality: "Chiropractic",
      visitapproved: "8",
      visitremaining: "4",
      notes: "Approved for 8 Visits",
      status: true,
    },

    {
      authorization: "424836598",
      procedurecodes: "92597",
      startdate: "Jul 12 2019",
      enddate: "Nov 17 2020",
      speciality: "Obesity",
      visitapproved: "8",
      visitremaining: "3",
      notes: "Approved for 8 Visits",
      status: false,
    },
    {
      authorization: "735570014",
      procedurecodes: "97803",
      startdate: "May 10 2021",
      enddate: "Nov 19 2022",
      speciality: "Gastroenterology",
      visitapproved: "8",
      visitremaining: "4",
      notes: "Approved for 8 Visits",
      status: false,
    },
    {
      authorization: "339342368",
      procedurecodes: "99236",
      startdate: "Jun 17 2018",
      enddate: "Apr 12 2022",
      speciality: "Neurology",
      visitapproved: "8",
      visitremaining: "2",
      notes: "Approved for 8 Visits",
      status: false,
    },
    {
      authorization: "424836598",
      procedurecodes: "98943",
      startdate: "Nov 12 2021",
      enddate: "Nov 12 2021",
      speciality: "Anesthesiologist",
      visitapproved: "8",
      visitremaining: "4",
      notes: "Approved for 8 Visits",
      status: false,
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};
