export const consentforms = {
  content: [
    {
      title: "Consent for Telahealth Consultation",
      owner: "Roman Morales",
      mandatory: false,
      assignedbydefault: true,
    },
    {
      title: "Notice of Privacy Practices",
      owner: "Marc Mckinney",
      mandatory: false,
      assignedbydefault: true,
    },
    {
      title: "Practice Policies",
      owner: "Roderick Cobb",
      mandatory: true,
      assignedbydefault: false,
    },
    {
      title: "Consent for Telahealth Consultation",
      owner: "Roman Morales",
      mandatory: true,
      assignedbydefault: false,
    },
    {
      title: "Notice of Privacy Practices",
      owner: "Ronald Douglas",
      mandatory: true,
      assignedbydefault: true,
    },
    {
      title: "Consent for Telahealth Consultation",
      owner: "Roman Morales",
      mandatory: false,
      assignedbydefault: true,
    },
    {
      title: "Notice of Privacy Practices",
      owner: "Marc Mckinney",
      mandatory: false,
      assignedbydefault: false,
    },
    {
      title: "Practice Policies",
      owner: "Roderick Cobb",
      mandatory: true,
      assignedbydefault: false,
    },
    {
      title: "Consent for Telahealth Consultation",
      owner: "Roman Morales",
      mandatory: true,
      assignedbydefault: false,
    },
    {
      title: "Notice of Privacy Practices",
      owner: "Ronald Douglas",
      mandatory: false,
      assignedbydefault: false,
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};
