export const feeSchedule = [
    {
        codeType: 'CPT',
        procedureCode: '90846 - Family Psychotherapy without patient present',
        provider: 'Ginny Weasley',
        state: 'Alabama',
        price: '$ 200',
        modifiers: 'NA',
        ndcCode: 'NA',
        ndcUnit: 'NA',
        status: 'Active',
        action: ''
    },
    {
        codeType: 'HCPCS',
        procedureCode: '90849 - Multiple-family group psychotherapy',
        provider: 'Harry Potter',
        state: 'Alaska',
        price: '$ 120',
        modifiers: 'NA',
        ndcCode: 'NA',
        ndcUnit: 'NA',
        status: 'Inactive',
        action: ''
    },
    {
        codeType: 'CPT',
        procedureCode: '96105 - Assessment of Aphasia',
        provider: 'Ron Wisllie',
        state: 'California',
        price: '$ 290',
        modifiers: 'NA',
        ndcCode: 'NA',
        ndcUnit: 'NA',
        status: 'Active',
        action: ''
    },
    {
        codeType: 'HCPCS',
        procedureCode: '96116 - Psychiatric Diagnostic Evaluation with Medical',
        provider: 'Annie Effertz',
        state: 'Missouri',
        price: '$ 190',
        modifiers: 'NA',
        ndcCode: 'NA',
        ndcUnit: 'NA',
        status: 'Inactive',
        action: ''
    },
    {
        codeType: 'CPT',
        procedureCode: '90846 - Family Psychotherapy without patient present',
        provider: 'Ludo Bagman',
        state: 'Alabama',
        price: '$ 210',
        modifiers: 'NA',
        ndcCode: 'NA',
        ndcUnit: 'NA',
        status: 'Active',
        action: ''
    },
    {
        codeType: 'HCPCS',
        procedureCode: '90849 - Multiple-family group psychotherapy',
        provider: 'Ron Wisllie',
        state: 'Alaska',
        price: '$ 170',
        modifiers: 'NA',
        ndcCode: 'NA',
        ndcUnit: 'NA',
        status: 'Inactive',
        action: ''
    },
    {
        codeType: 'CPT',
        procedureCode: '96105 - Assessment of Aphasia',
        provider: 'Jocelyn vetroves',
        state: 'Alabama',
        price: '$ 290',
        modifiers: 'NA',
        ndcCode: 'NA',
        ndcUnit: 'NA',
        status: 'Active',
        action: ''
    },
    {
        codeType: 'HCPCS',
        procedureCode: '96116 - Psychiatric Diagnostic Evaluation with Medical',
        provider: 'Monica Geller',
        state: 'Alaska',
        price: '$ 150',
        modifiers: 'NA',
        ndcCode: 'NA',
        ndcUnit: 'NA',
        status: 'Inactive',
        action: ''
    },
    {
        codeType: 'CPT',
        procedureCode: '90846 - Family Psychotherapy without patient present',
        provider: 'Ryan Weste',
        state: 'California',
        price: '$ 400',
        modifiers: 'NA',
        ndcCode: 'NA',
        ndcUnit: 'NA',
        status: 'Active',
        action: ''
    },
    {
        codeType: 'HCPCS',
        procedureCode: '90849 - Multiple-family group psychotherapy',
        provider: 'Eladia Chapin',
        state: 'Missouri',
        price: '$ 250',
        modifiers: 'NA',
        ndcCode: 'NA',
        ndcUnit: 'NA',
        status: 'Inactive',
        action: ''
    },
]