export const medicationsdata = {
  content: [
    {
      medication: "Amoxicillin 500mg tablet",
      prescriber: "Kerry Johnston",
      dosage: "Take 1 tablet every 8 hours by oral route in the morning",
      route: "Topical",
      startdate: "04-10-2022",
      enddate: "26-10-2022",
      status: true,
      action: true,
    },
    {
      medication: "Augmentin 625 Duo Tablet",
      prescriber: "Karl Zimmerman",
      dosage: "Take 2 tablet every 10 hours by oral route in the morning",
      route: "Intravenous",
      startdate: "04-10-2022",
      enddate: "10-11-2022",
      status: true,
      action: true,
    },
    {
      medication: "Amoxicillin 500mg tablet",
      prescriber: "Monica Geller",
      dosage: "Take 1 tablet every 8 hours by oral route in the morning",
      route: "Topical",
      startdate: "04-10-2022",
      enddate: "26-10-2022",
      status: false,
      action: true,
    },
    {
      medication: "Augmentin 625 Duo Tablet",
      prescriber: "Ross Geller",
      dosage: "Take 2 tablet every 10 hours by oral route in the morning",
      route: "Intravenous",
      startdate: "04-10-2022",
      enddate: "10-11-2022",
      status: false,
      action: true,
    },
    {
      medication: "Augmentin 625 Duo Tablet",
      prescriber: "Karl Zimmerman",
      dosage: "Take 2 tablet every 10 hours by oral route in the morning",
      route: "Intravenous",
      startdate: "04-10-2022",
      enddate: "10-11-2022",
      status: true,
      action: true,
    },
    {
      medication: "Amoxicillin 500mg tablet",
      prescriber: "Monica Geller",
      dosage: "Take 1 tablet every 8 hours by oral route in the morning",
      route: "Topical",
      startdate: "04-10-2022",
      enddate: "26-10-2022",
      status: false,
      action: true,
    },
    {
      medication: "Augmentin 625 Duo Tablet",
      prescriber: "Ross Geller",
      dosage: "Take 2 tablet every 10 hours by oral route in the morning",
      route: "Intravenous",
      startdate: "04-10-2022",
      enddate: "10-11-2022",
      status: false,
      action: true,
    },
    {
      medication: "Augmentin 625 Duo Tablet",
      prescriber: "Karl Zimmerman",
      dosage: "Take 2 tablet every 10 hours by oral route in the morning",
      route: "Intravenous",
      startdate: "04-10-2022",
      enddate: "10-11-2022",
      status: true,
      action: true,
    },
    {
      medication: "Amoxicillin 500mg tablet",
      prescriber: "Monica Geller",
      dosage: "Take 1 tablet every 8 hours by oral route in the morning",
      route: "Topical",
      startdate: "04-10-2022",
      enddate: "26-10-2022",
      status: false,
      action: true,
    },
    {
      medication: "Augmentin 625 Duo Tablet",
      prescriber: "Ross Geller",
      dosage: "Take 2 tablet every 10 hours by oral route in the morning",
      route: "Intravenous",
      startdate: "04-10-2022",
      enddate: "10-11-2022",
      status: false,
      action: true,
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};

export const patientmedicationsdata = {
  content: [
    {
      medication: "Amoxicillin 500mg tablet",
      prescriber: "Monica Geller",
      note: "Take 1 tablet every 8 hours by oral route in the morning",
    },
    {
      medication: "Augmentin 625 Duo Tablet",
      prescriber: "Karl Zimmerman",
      note: "Take 2 tablet every 10 hours by oral route in the morning",
    },
    {
      medication: "Amoxicillin 500mg tablet",
      prescriber: "Monica Geller",
      note: "Take 1 tablet every 8 hours by oral route in the morning",
    },
    {
      medication: "Augmentin 625 Duo Tablet",
      prescriber: "Ross Geller",
      note: "Take 2 tablet every 10 hours by oral route in the morning",
    },
    {
      medication: "Augmentin 625 Duo Tablet",
      prescriber: "Karl Zimmerman",
      note: "Take 2 tablet every 10 hours by oral route in the morning",
    },
    {
      medication: "Amoxicillin 500mg tablet",
      prescriber: "Monica Geller",
      note: "Take 1 tablet every 8 hours by oral route in the morning",
    },
    {
      medication: "Augmentin 625 Duo Tablet",
      prescriber: "Ross Geller",
      note: "Take 2 tablet every 10 hours by oral route in the morning",
    },
    {
      medication: "Augmentin 625 Duo Tablet",
      prescriber: "Karl Zimmerman",
      note: "Take 2 tablet every 10 hours by oral route in the morning",
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};
