export const MyAppointmentsData = [
  {
    key: 1,
    date: new Date(),
    timeRange: "10.30 AM - 11.30 AM",
    providerName: "Dr. Professor",
    role: "Dermatology",
    locations: "Location 1",
    appointmentType: "New Appointment",
    reasonForVisit: "Sudden onset of high fever.",
    intakeFormStatus: "SUBMITTED",
    copay: "$20",
    status: "COMPLETED",
  },
  {
    key: 2,
    date: new Date(),
    timeRange: "10.30 AM - 11.30 AM",
    providerName: "Dr. Ross Geller",
    role: "Dermatology",
    locations: "Location 1",
    appointmentType: "New Appointment",
    reasonForVisit: "Headache, muscle aches and joint pain.",
    intakeFormStatus: "NOT_SUBMITTED",
    copay: "$20",
    status: "SCHEDULED",
  },
  {
    key: 3,
    date: new Date(),
    timeRange: "10.30 AM - 11.30 AM",
    providerName: "Dr. John Doe",
    role: "Dermatology",
    locations: "Location 1",
    appointmentType: "Follow Up ",
    reasonForVisit: "Nasal congestion and runny nose.",
    intakeFormStatus: "SUBMITTED",
    copay: "$20",
    status: "PENDING",
  },
  {
    key: 4,
    date: new Date(),
    timeRange: "10.30 AM - 11.30 AM",
    providerName: "Dr. Monica Geller",
    role: "Dermatology",
    locations: "Location 1",
    appointmentType: "New Appointment",
    reasonForVisit: "Sudden onset of high fever.",
    intakeFormStatus: "SUBMITTED",
    copay: "$20",
    status: "CANCELLED",
  },
  {
    key: 5,
    date: new Date(),
    timeRange: "10.30 AM - 11.30 AM",
    providerName: "Dr. Alexander",
    role: "Dermatology",
    locations: "Location 1",
    appointmentType: "Follow Up ",
    reasonForVisit: "Headache, muscle aches and joint pain.",
    intakeFormStatus: "SUBMITTED",
    copay: "$20",
    status: "COMPLETED",
  },
];

export const PastAppointmentsData = [
  {
    key: 1,
    date: new Date(),
    timeRange: "8:30PM",
    providerName: "Dr. John",
    role: "Dermatology",
    appointmentType: "New Appointment",
    reason: "Infection Disease",
    appointmentStatus: "COMPLETED",
    billStatus: "PAID",
  },
  {
    key: 2,
    date: new Date(),
    timeRange: "2:30PM",
    providerName: "John Doe",
    role: "Anesthesiology",
    appointmentType: "New Appointment",
    reason: "Cough & Fever",
    appointmentStatus: "CANCEL",
    billStatus: "",
  },
  {
    key: 3,
    date: new Date(),
    timeRange: "2:30PM",
    providerName: "Dr. Chandler Bing",
    role: "Neurology",
    appointmentType: "New Appointment",
    reason: "Skin Infection",
    appointmentStatus: "COMPLETED",
    billStatus: "PENDING",
  },
];
