export const problemsforms = {
  content: [
    {
      problems: "A01.00- Typhoid fever",
      type: "Chronic",
      diagnoseddate: "04-10-2022",
      updateddate: "04-10-2022",
      status: true,
      note: "Patient has Typhoid fever",
      action: true,
    },
    {
      problems: "A15.9- Respiratory tuberculosis unspecified",
      type: "Acute",
      diagnoseddate: "10-10-2022",
      updateddate: "04-10-2022",
      status: false,
      note: "Patient has Respiratory tuberculosis unspecified",
      action: true,
    },
    {
      problems: "A66.6- Bone and joint lesions of yaws",
      type: "Acute",
      diagnoseddate: "10-10-2022",
      updateddate: "04-10-2022",
      status: false,
      note: "Patient has Bone and joint lesions of yaws",
      action: true,
    },
    {
      problems: "A01.00- Typhoid fever",
      type: "Chronic",
      diagnoseddate: "04-10-2022",
      updateddate: "04-10-2022",
      status: true,
      note: "Patient has Typhoid fever",
      action: true,
    },
    {
      problems: "A15.9- Respiratory tuberculosis unspecified",
      type: "Acute",
      diagnoseddate: "10-10-2022",
      updateddate: "04-10-2022",
      status: true,
      note: "Patient has Respiratory tuberculosis unspecified",
      action: true,
    },
    {
      problems: "A66.6- Bone and joint lesions of yaws",
      type: "Acute",
      diagnoseddate: "10-10-2022",
      updateddate: "04-10-2022",
      status: false,
      note: "Patient has Bone and joint lesions of yaws",
      action: true,
    },
    {
      problems: "A01.00- Typhoid fever",
      type: "Chronic",
      diagnoseddate: "04-10-2022",
      updateddate: "04-10-2022",
      status: true,
      note: "Patient has Typhoid fever",
      action: true,
    },
    {
      problems: "A15.9- Respiratory tuberculosis unspecified",
      type: "Acute",
      diagnoseddate: "10-10-2022",
      updateddate: "04-10-2022",
      status: true,
      note: "Patient has Respiratory tuberculosis unspecified",
      action: true,
    },
    {
      problems: "A66.6- Bone and joint lesions of yaws",
      type: "Acute",
      diagnoseddate: "10-10-2022",
      updateddate: "04-10-2022",
      status: false,
      note: "Patient has Typhoid fever",
      action: true,
    },
    {
      problems: "A01.00- Typhoid fever",
      type: "Chronic",
      diagnoseddate: "04-10-2022",
      updateddate: "04-10-2022",
      status: true,
      note: "Patient has Typhoid fever",
      action: true,
    },
    {
      problems: "A15.9- Respiratory tuberculosis unspecified",
      type: "Acute",
      diagnoseddate: "10-10-2022",
      updateddate: "04-10-2022",
      status: true,
      note: "Patient has Typhoid fever",
      action: true,
    },
    {
      problems: "A66.6- Bone and joint lesions of yaws",
      type: "Acute",
      diagnoseddate: "10-10-2022",
      updateddate: "04-10-2022",
      status: false,
      note: "Patient has Typhoid fever",
      action: true,
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};

export const patientproblemsforms = {
  content: [
    {
      problems: "A01.00- Typhoid fever",
      provider: "Corina Smith",
      type: "Chronic",
      note: "Patient has Typhoid fever",
    },
    {
      problems: "A15.9- Respiratory tuberculosis unspecified",
      provider: "Monica Geller",
      type: "Acute",
      note: "Patient has Respiratory tuberculosis unspecified",
    },
    {
      problems: "A66.6- Bone and joint lesions of yaws",
      provider: "Gina Tribbiani",
      type: "Acute",
      note: "Patient has Bone and joint lesions of yaws",
    },
    {
      problems: "A01.00- Typhoid fever",
      provider: "Gina Tribbiani",
      type: "Chronic",
      note: "Patient has Typhoid fever",
    },
    {
      problems: "A15.9- Respiratory tuberculosis unspecified",
      provider: "Gina Tribbiani",
      type: "Acute",
      note: "Patient has Respiratory tuberculosis unspecified",
    },
    {
      problems: "A66.6- Bone and joint lesions of yaws",
      provider: "Gina Tribbiani",
      type: "Acute",
      note: "Patient has Bone and joint lesions of yaws",
    },
    {
      problems: "A01.00- Typhoid fever",
      provider: "Gina Tribbiani",
      type: "Chronic",
      note: "Patient has Typhoid fever",
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};
