export const superBillData = {
  content: [
    {
      id: "A7892",
      dateOfService: "10-7-2022",
      legalFirstName: "Kiran",
      legalLastName: "Rathod",
      age: "52",
      provider: {
        firstName: "Dr.Geller",
        lastName: "Para",
      },
      location: {
        id: 1,
        uuid: "ed9717b0-173f-44b1-99b1-eb83da8006cc",
        locationId: "78",
        name: "Jeet health care",
        specialities: [
          {
            id: 1,
            name: "Cardiology",
          },
        ],
      },
      contactNumber: "9966558899",
      code: "99253 - New appointment",
      charges: "$100",
      qty: "2",
      totalCharges: "$152",
      patientBalance: true,
      patientBalanceAmount: "$52",
      isuranceBalance: true,
      isuranceBalanceAmount: "$100",
      appointmentType: "New Appointment",
      reasonForVisit: "Cough & Fever",
      serviceLocation: "Location 1",
      visitID: "V7452",
    },
    {
      id: "S7416",
      dateOfService: "10-7-2022",
      legalFirstName: "Demelza",
      legalLastName: " Robins (A324)",
      age: "45",
      provider: {
        firstName: "Dr. Corina",
        lastName: "",
      },
      location: {
        id: 1,
        uuid: "ed9717b0-173f-44b1-99b1-eb83da8006cc",
        locationId: "78",
        name: "Jeet health care",
        specialities: [
          {
            id: 1,
            name: "Dermatology",
          },
        ],
      },
      contactNumber: "(235) 143-3243",
      code: "81003 - Urinalysis Auto W/O Scope ",
      charges: "$100",
      qty: "2",
      totalCharges: "$152",
      patientBalance: false,
      patientBalanceAmount: "$52",
      isuranceBalance: false,
      isuranceBalanceAmount: "$100",
      appointmentType: " Follow Up",
      reasonForVisit: "Infection Disease",
      serviceLocation: "Location 2",
      visitID: "V0523",
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
};

export const patientPaymentData = {
  content: [
    {
      id: "A7892",
      dateOfService: "10-7-2022",
      legalFirstName: "Kiran",
      legalLastName: "Rathod",
      age: "52",
      provider: {
        firstName: "Dr.Geller",
        lastName: "Para",
      },
      location: {
        id: 1,
        uuid: "ed9717b0-173f-44b1-99b1-eb83da8006cc",
        locationId: "78",
        name: "Jeet health care",
        specialities: [
          {
            id: 1,
            name: "Cardiology",
          },
        ],
      },
      contactNumber: "9966558899",
      code: "99253 - New appointment",
      charges: "$100",
      qty: "2",
      totalCharges: "$152",
      patientBalance: true,
      patientBalanceAmount: "$52",
      isuranceBalance: true,
      isuranceBalanceAmount: "$100",
      appointmentType: "New Appointment",
      reasonForVisit: "Cough & Fever",
      serviceLocation: "Location 1",
      visitID: "V7452",
      superbillID: "S34533",
      gender: "Male",
      paymentId: "29322",
      paymentMethod: "Check",
      transitionId: "2343242224",
      transitionDate: "Tue Mar 01 2022",
      paidAmount: "$300",
      appliedAmount: "$300",
      unAppliedAmount: "$300",
    },
    {
      id: "S7416",
      dateOfService: "10-7-2022",
      legalFirstName: "Demelza",
      legalLastName: " Robins (A324)",
      age: "45",
      provider: {
        firstName: "Dr. Corina",
        lastName: "",
      },
      location: {
        id: 1,
        uuid: "ed9717b0-173f-44b1-99b1-eb83da8006cc",
        locationId: "78",
        name: "Jeet health care",
        specialities: [
          {
            id: 1,
            name: "Dermatology",
          },
        ],
      },
      contactNumber: "(235) 143-3243",
      code: "81003 - Urinalysis Auto W/O Scope ",
      charges: "$100",
      qty: "2",
      totalCharges: "$152",
      patientBalance: false,
      patientBalanceAmount: "$52",
      isuranceBalance: false,
      isuranceBalanceAmount: "$100",
      appointmentType: " Follow Up",
      reasonForVisit: "Infection Disease",
      serviceLocation: "Location 2",
      visitID: "V57643",
      superbillID: "S29878",
      gender: "Male",
      paymentId: "85212",
      paymentMethod: "EFT",
      transitionId: "2372379239",
      transitionDate: "Mon Aug 09 2021",
      paidAmount: "$450",
      appliedAmount: "$450",
      unAppliedAmount: "$450",
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
};

export const insurancePaymentData = {
  content: [
    {
      id: "A7892",
      dateOfService: "10-7-2022",
      legalFirstName: "Henna",
      legalLastName: "West",
      age: "52",
      provider: {
        firstName: "Dr.Geller",
        lastName: "Para",
      },
      location: {
        id: 1,
        uuid: "ed9717b0-173f-44b1-99b1-eb83da8006cc",
        locationId: "78",
        name: "Jeet health care",
        specialities: [
          {
            id: 1,
            name: "Cardiology",
          },
        ],
      },
      contactNumber: "9966558899",
      appointmentType: "New Appointment",
      visitID: "V7452",
      superbillID: "S34533",
      gender: "Male",
      paymentId: "29322",
      paymentMethod: "Check",
      transitionId: "2343242224",
      transitionDate: "Tue Mar 01 2022",
      paidAmount: "$300",
      appliedAmount: "$300",
      unAppliedAmount: "$300",
      payerName: "United Health",
    },
    {
      id: "S7416",
      dateOfService: "10-7-2022",
      legalFirstName: "Demelza",
      legalLastName: " Robins (A324)",
      age: "45",
      provider: {
        firstName: "Dr. Corina",
        lastName: "",
      },
      location: {
        id: 1,
        uuid: "ed9717b0-173f-44b1-99b1-eb83da8006cc",
        locationId: "78",
        name: "Jeet health care",
        specialities: [
          {
            id: 1,
            name: "Dermatology",
          },
        ],
      },
      contactNumber: "(235) 143-3243",
      visitID: "V57643",
      superbillID: "S29878",
      gender: "Female",
      paymentId: "85212",
      paymentMethod: "EFT",
      transitionId: "2372379239",
      transitionDate: "Mon Aug 09 2021",
      paidAmount: "$450",
      appliedAmount: "$450",
      unAppliedAmount: "$450",
      payerName: "Molina Healthcare",
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
};

export const patientAccountReceivableData = {
  content: [
    {
      id: "A7892",
      dateOfService: "10-7-2022",
      legalFirstName: "Henna",
      legalLastName: "West",
      age: "52",
      provider: {
        firstName: "Dr.Geller",
        lastName: "Para",
      },
      location: {
        id: 1,
        uuid: "ed9717b0-173f-44b1-99b1-eb83da8006cc",
        locationId: "78",
        name: "Jeet health care",
        specialities: [
          {
            id: 1,
            name: "Cardiology",
          },
        ],
      },
      contactNumber: "9966558899",
      gender: "Female",
      zeroToThirtydays: "$10",
      thirtyOneToSixtydays: "$45",
      sixtyOneTonintydays: "$52",
      nintyOneToOneTwentydays: "$12",
      oneTwentyDays: "$11",
      total: "$130",
      payerId: "A852",
      payerName: "Hartford Financial Services Group",
    },
    {
      id: "S7416",
      dateOfService: "10-7-2022",
      legalFirstName: "Demelza",
      legalLastName: " Robins (A324)",
      age: "45",
      provider: {
        firstName: "Dr. Corina",
        lastName: "",
      },
      location: {
        id: 1,
        uuid: "ed9717b0-173f-44b1-99b1-eb83da8006cc",
        locationId: "78",
        name: "Jeet health care",
        specialities: [
          {
            id: 1,
            name: "Dermatology",
          },
        ],
      },
      gender: "Female",
      contactNumber: "(235) 143-3243",
      zeroToThirtydays: "$10",
      thirtyOneToSixtydays: "$45",
      sixtyOneTonintydays: "$52",
      nintyOneToOneTwentydays: "$12",
      oneTwentyDays: "$11",
      total: "$130",
      payerId: "A4520",
      payerName: "Farmers Insurance",
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
};

export const insuranceMainAccountReceivableData = {
  content: [
    {
      total: "Total",
      zeroToThirtydays: "$150",
      thirtyOneToSixtydays: "$50",
      sixtyOneTonintydays: "$56",
      nintyOneToOneTwentydays: "$250",
      oneTwentyDays: "$562",
      grandTotal: "$15620",
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
};

export const summaryAccountReceivableData = {
  content: [
    {
      total: "Total",
      zeroToThirtydays: "$150",
      thirtyOneToSixtydays: "$50",
      sixtyOneTonintydays: "$56",
      nintyOneToOneTwentydays: "$250",
      oneTwentyDays: "$562",
      grandTotal: "$15620",
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
};

export const providerPatientList = {
  date: "2023-08-08T11:51:36.672+00:00",
  code: "OK",
  message: "Audit log found successfully",
  data: [
    {
      id: 1,
      provider: "Kendal Luce",
      dob: '01-05-1970',
      lVisit:"Sep 4,2023",
      nVisit:"Sep 5,2023",
      status: true,
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Ron Weasley",
      email: "mail@email.com",
      phoneNumber: "(235) 143-3243",
      validInsurance:"Yes",
      specialities: 'Otorhinolaryngology, Obesity',
      gender: 'Male'
    },
    {
      id: 2,
      provider: "Kendal Luce",
      dob: '01-05-1970',
      lVisit:"Sep 4,2023",
      nVisit:"Sep 5,2023",
      status: false,
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Annie Effertz",
      email: "mail@email.com",
      phoneNumber: "(235) 143-3243",
      validInsurance:"Yes",
      specialities: 'Otorhinolaryngology, Obesity',
      gender: 'Female'
    },
    {
      id: 3,
      provider: "Kendal Luce",
      dob: '01-05-1970',
      lVisit:"Sep 4,2023",
      nVisit:"Sep 5,2023",
      status: false,
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Mary Riddle",
      email: "mail@email.com",
      phoneNumber: "(235) 143-3243",
      validInsurance:"Yes",
      specialities: 'Otorhinolaryngology, Obesity',
      gender: 'Female'
    },
    {
      id: 4,
      provider: "Kendal Luce",
      dob: '01-05-1970',
      lVisit:"Sep 4,2023",
      nVisit:"Sep 5,2023",
      status: true,
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Ludo Bagman",
      email: "mail@email.com",
      phoneNumber: "(235) 143-3243",
      validInsurance:"Yes",
      specialities: 'Otorhinolaryngology, Obesity',
      gender: 'Male'
    },
    {
      id: 5,
      provider: "Kendal Luce",
      dob: '01-05-1970',
      lVisit:"Sep 4,2023",
      nVisit:"Sep 5,2023",
      status: false,
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Loretta Ratke",
      email: "mail@email.com",
      phoneNumber: "(235) 143-3243",
      validInsurance:"Yes",
      specialities: 'Otorhinolaryngology, Obesity',
      gender: 'Female'
    },
    {
      id: 6,
      provider: "Kendal Luce",
      dob: '01-05-1970',
      lVisit:"Sep 4,2023",
      nVisit:"Sep 5,2023",
      status: false,
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Grant Bartoletti",
      email: "mail@email.com",
      phoneNumber: "(235) 143-3243",
      validInsurance:"Yes",
      specialities: 'Otorhinolaryngology, Obesity',
      gender: 'Male'
    },{
      id: 7,
      provider: "Kendal Luce",
      dob: '01-05-1970',
      lVisit:"Sep 4,2023",
      nVisit:"Sep 5,2023",
      status: false,
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Harry Potter",
      email: "mail@email.com",
      phoneNumber: "(235) 143-3243",
      validInsurance:"Yes",
      specialities: 'Otorhinolaryngology, Obesity',
      gender: 'Male'
    },
    {
      id: 8,
      provider: "Kendal Luce",
      dob: '01-05-1970',
      lVisit:"Sep 4,2023",
      nVisit:"Sep 5,2023",
      status: false,
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Loretta Ratke",
      email: "mail@email.com",
      phoneNumber: "(235) 143-3243",
      validInsurance:"Yes",
      specialities: 'Otorhinolaryngology, Obesity',
      gender: 'Female'
    },
    {
      id: 9,
      provider: "Kendal Luce",
      dob: '01-05-1970',
      lVisit:"Sep 4,2023",
      nVisit:"Sep 5,2023",
      status: false,
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Ludo Bagman",
      email: "mail@email.com",
      phoneNumber: "(235) 143-3243",
      validInsurance:"Yes",
      specialities: 'Otorhinolaryngology, Obesity',
      gender: 'Male'
    },
    {
      id: 10,
      provider: "Kendal Luce",
      dob: '01-05-1970',
      lVisit:"Sep 4,2023",
      nVisit:"Sep 5,2023",
      status: false,
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Ginny Weasley",
      email: "mail@email.com",
      phoneNumber: "(235) 143-3243",
      validInsurance:"Yes",
      specialities: 'Otorhinolaryngology, Obesity',
      gender: 'Female'
    },
    {
      id: 11,
      provider: "Kendal Luce",
      dob: '01-05-1970',
      lVisit:"Sep 4,2023",
      nVisit:"Sep 5,2023",
      status: false,
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Ron Weasley",
      email: "mail@email.com",
      phoneNumber: "(235) 143-3243",
      validInsurance:"Yes",
      specialities: 'Otorhinolaryngology, Obesity',
      gender: 'Male'
    },
    {
      id: 12,
      provider: "Kendal Luce",
      dob: '01-05-1970',
      lVisit:"Sep 4,2023",
      nVisit:"Sep 5,2023",
      status: true,
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Ron Weasley",
      email: "mail@email.com",
      phoneNumber: "(235) 143-3243",
      validInsurance:"Yes",
      specialities: 'Otorhinolaryngology, Obesity',
      gender: 'Male'
    },
    {
      id: 13,
      provider: "Kendal Luce",
      dob: '01-05-1970',
      lVisit:"Sep 4,2023",
      nVisit:"Sep 5,2023",
      status: false,
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Annie Effertz",
      email: "mail@email.com",
      phoneNumber: "(235) 143-3243",
      validInsurance:"Yes",
      specialities: 'Otorhinolaryngology, Obesity',
      gender: 'Female'
    },
    {
      id: 14,
      provider: "Kendal Luce",
      dob: '01-05-1970',
      lVisit:"Sep 4,2023",
      nVisit:"Sep 5,2023",
      status: false,
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Mary Riddle",
      email: "mail@email.com",
      phoneNumber: "(235) 143-3243",
      validInsurance:"Yes",
      specialities: 'Otorhinolaryngology, Obesity',
      gender: 'Female'
    },
    {
      id: 15,
      provider: "Kendal Luce",
      dob: '01-05-1970',
      lVisit:"Sep 4,2023",
      nVisit:"Sep 5,2023",
      status: true,
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Ludo Bagman",
      email: "mail@email.com",
      phoneNumber: "(235) 143-3243",
      validInsurance:"Yes",
      specialities: 'Otorhinolaryngology, Obesity',
      gender: 'male'
    },
    {
      id: 16,
      provider: "Kendal Luce",
      dob: '01-05-1970',
      lVisit:"Sep 4,2023",
      nVisit:"Sep 5,2023",
      status: false,
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Loretta Ratke",
      email: "mail@email.com",
      phoneNumber: "(235) 143-3243",
      validInsurance:"Yes",
      specialities: 'Otorhinolaryngology, Obesity',
      gender: 'Female'
    },
    {
      id: 17,
      provider: "Kendal Luce",
      dob: '01-05-1970',
      lVisit:"Sep 4,2023",
      nVisit:"Sep 5,2023",
      status: false,
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Grant Bartoletti",
      email: "mail@email.com",
      phoneNumber: "(235) 143-3243",
      validInsurance:"Yes",
      specialities: 'Otorhinolaryngology, Obesity',
      gender: 'Male'
    },{
      id: 18,
      provider: "Kendal Luce",
      dob: '01-05-1970',
      lVisit:"Sep 4,2023",
      nVisit:"Sep 5,2023",
      status: false,
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Harry Potter",
      email: "mail@email.com",
      phoneNumber: "(235) 143-3243",
      validInsurance:"Yes",
      specialities: 'Otorhinolaryngology, Obesity',
      gender: 'Male'
    },
    {
      id: 19,
      provider: "Kendal Luce",
      dob: '01-05-1970',
      lVisit:"Sep 4,2023",
      nVisit:"Sep 5,2023",
      status: false,
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Loretta Ratke",
      email: "mail@email.com",
      phoneNumber: "(235) 143-3243",
      validInsurance:"Yes",
      specialities: 'Otorhinolaryngology, Obesity',
      gender: 'Female'
    },
    {
      id: 20,
      provider: "Kendal Luce",
      dob: '01-05-1970',
      lVisit:"Sep 4,2023",
      nVisit:"Sep 5,2023",
      status: false,
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Ludo Bagman",
      email: "mail@email.com",
      phoneNumber: "(235) 143-3243",
      validInsurance:"Yes",
      specialities: 'Otorhinolaryngology, Obesity',
      gender: 'Male'
    },
    {
      id: 21,
      provider: "Kendal Luce",
      dob: '01-05-1970',
      lVisit:"Sep 4,2023",
      nVisit:"Sep 5,2023",
      status: false,
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Ginny Weasley",
      email: "mail@email.com",
      phoneNumber: "(235) 143-3243",
      validInsurance:"Yes",
      specialities: 'Otorhinolaryngology, Obesity',
      gender: 'Female'
    },
    {
      id: 22,
      provider: "Kendal Luce",
      dob: '01-05-1970',
      lVisit:"Sep 4,2023",
      nVisit:"Sep 5,2023",
      status: false,
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Ron Weasley",
      email: "mail@email.com",
      phoneNumber: "(235) 143-3243",
      validInsurance:"Yes",
      specialities: 'Otorhinolaryngology, Obesity',
      gender: 'Female'
    }
  ],
  path: "/api/admin/migration/audit-log/PROVIDER_DATA",
  requestId: "e2c3d6ec-6afc-4a6a-aaaf-26a530948af1",
  version: "1.0",
};

export const providerPatientPaymentList = {
  date: "2023-08-08T11:51:36.672+00:00",
  code: "OK",
  message: "Audit log found successfully",
  data: [
    {
      id:1,
      visitId: "V123",
      superBillId: "S89123",
      paymentId:"97567",
      paymentMethod:"Cheque",
      transactionId:"9876543216",
      transactionDate:"Mon sep 11 2023",
      paidAmount: "$200",
      appliedAmount:"$100",
      unAppliedAmount:"$100",
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Ron Weasley (A987)",
      age: "25 yrs",
      gender: "Male",
    },
    {
      id:2,
      visitId: "V123",
      superBillId: "S89123",
      paymentId:"97567",
      paymentMethod:"Cheque",
      transactionId:"9876543216",
      transactionDate:"Mon sep 11 2023",
      paidAmount: "$200",
      appliedAmount:"$100",
      unAppliedAmount:"$100",
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Ron Weasley (A987)",
      age: "25 yrs",
      gender: "Male",
    },
    {
      id:3,
      visitId: "V123",
      superBillId: "S89123",
      paymentId:"97567",
      paymentMethod:"Cheque",
      transactionId:"9876543216",
      transactionDate:"Mon sep 11 2023",
      paidAmount: "$200",
      appliedAmount:"$100",
      unAppliedAmount:"$100",
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Ron Weasley (A987)",
      age: "25 yrs",
      gender: "Male",
    },
    {
      id:4,
      visitId: "V123",
      superBillId: "S89123",
      paymentId:"97567",
      paymentMethod:"Cheque",
      transactionId:"9876543216",
      transactionDate:"Mon sep 11 2023",
      paidAmount: "$200",
      appliedAmount:"$100",
      unAppliedAmount:"$100",
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Ron Weasley (A987)",
      age: "25 yrs",
      gender: "Male",
    },
    {
      id:5,
      visitId: "V123",
      superBillId: "S89123",
      paymentId:"97567",
      paymentMethod:"Cheque",
      transactionId:"9876543216",
      transactionDate:"Mon sep 11 2023",
      paidAmount: "$200",
      appliedAmount:"$100",
      unAppliedAmount:"$100",
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Ron Weasley (A987)",
      age: "25 yrs",
      gender: "Male",
    },
    {
      id:6,
      visitId: "V123",
      superBillId: "S89123",
      paymentId:"97567",
      paymentMethod:"Cheque",
      transactionId:"9876543216",
      transactionDate:"Mon sep 11 2023",
      paidAmount: "$200",
      appliedAmount:"$100",
      unAppliedAmount:"$100",
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Ron Weasley (A987)",
      age: "25 yrs",
      gender: "Male",
    },  
    {
      id:7,
      visitId: "V123",
      superBillId: "S89123",
      paymentId:"97567",
      paymentMethod:"Cheque",
      transactionId:"9876543216",
      transactionDate:"Mon sep 11 2023",
      paidAmount: "$200",
      appliedAmount:"$100",
      unAppliedAmount:"$100",
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Ron Weasley (A987)",
      age: "25 yrs",
      gender: "Male",
    },
    {
      id:8,
      visitId: "V123",
      superBillId: "S89123",
      paymentId:"97567",
      paymentMethod:"Cheque",
      transactionId:"9876543216",
      transactionDate:"Mon sep 11 2023",
      paidAmount: "$200",
      appliedAmount:"$100",
      unAppliedAmount:"$100",
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Ron Weasley (A987)",
      age: "25 yrs",
      gender: "Male",
    },
    {
      id:9,
      visitId: "V123",
      superBillId: "S89123",
      paymentId:"97567",
      paymentMethod:"Cheque",
      transactionId:"9876543216",
      transactionDate:"Mon sep 11 2023",
      paidAmount: "$200",
      appliedAmount:"$100",
      unAppliedAmount:"$100",
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Ron Weasley (A987)",
      age: "25 yrs",
      gender: "Male",
    },
    {
      id:10,
      visitId: "V123",
      superBillId: "S89123",
      paymentId:"97567",
      paymentMethod:"Cheque",
      transactionId:"9876543216",
      transactionDate:"Mon sep 11 2023",
      paidAmount: "$200",
      appliedAmount:"$100",
      unAppliedAmount:"$100",
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Ron Weasley (A987)",
      age: "25 yrs",
      gender: "Male",
    },
    {
      id:11,
      visitId: "V123",
      superBillId: "S89123",
      paymentId:"97567",
      paymentMethod:"Cheque",
      transactionId:"9876543216",
      transactionDate:"Mon sep 11 2023",
      paidAmount: "$200",
      appliedAmount:"$100",
      unAppliedAmount:"$100",
      patientImage: "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      patientName: "Ron Weasley (A987)",
      age: "25 yrs",
      gender: "Male",
    },
  ],
  path: "/api/admin/migration/audit-log/PROVIDER_DATA",
  requestId: "e2c3d6ec-6afc-4a6a-aaaf-26a530948af1",
  version: "1.0",
};