export const locationMockData = [
  {
    locationID: "1",
    locationName: "Medical Center A",
    specialities: "Cardiology, Neurology",
    Address: "123 Main Street",
    city: "Cityville",
    state: "Stateville",
    zipcode: "12345",
    contact: "555-123-4567",
    status: "<CustomSwitch checked={true} />",
    action: "<ModeEditOutlineOutlinedIcon />",
    departmentAdmin:"Steve Rogers"
  },
  {
    locationID: "2",
    locationName: "Health Clinic B",
    specialities: "Dermatology, Pediatrics",
    Address: "456 Elm Avenue",
    city: "Townville",
    state: "Stateville",
    zipcode: "67890",
    contact: "555-987-6543",
    status: "<CustomSwitch checked={false} />",
    action: "<ModeEditOutlineOutlinedIcon />",
    departmentAdmin:"John Doe"

  },
  {
    locationID: "3",
    locationName: "Wellness Center C",
    specialities: "Orthopedics, Internal Medicine",
    Address: "789 Oak Street",
    city: "Villageville",
    state: "Stateville",
    zipcode: "54321",
    contact: "555-456-7890",
    status: "<CustomSwitch checked={true} />",
    action: "<ModeEditOutlineOutlinedIcon />",
    departmentAdmin:"Austin Richard"
  },
  {
    locationID: "4",
    locationName: "Wellness Center C",
    specialities: "Orthopedics, Internal Medicine",
    Address: "789 Oak Street",
    city: "Villageville",
    state: "Stateville",
    zipcode: "54321",
    contact: "555-456-7890",
    status: "<CustomSwitch checked={true} />",
    action: "<ModeEditOutlineOutlinedIcon />",
    departmentAdmin:"Austin Richard"
  },
  {
    locationID: "5",
    locationName: "Wellness Center C",
    specialities: "Orthopedics, Internal Medicine",
    Address: "789 Oak Street",
    city: "Villageville",
    state: "Stateville",
    zipcode: "54321",
    contact: "555-456-7890",
    status: "<CustomSwitch checked={true} />",
    action: "<ModeEditOutlineOutlinedIcon />",
    departmentAdmin:"Austin Richard"
  },
  {
    locationID: "6",
    locationName: "Wellness Center C",
    specialities: "Orthopedics, Internal Medicine",
    Address: "789 Oak Street",
    city: "Villageville",
    state: "Stateville",
    zipcode: "54321",
    contact: "555-456-7890",
    status: "<CustomSwitch checked={true} />",
    action: "<ModeEditOutlineOutlinedIcon />",
    departmentAdmin:"Austin Richard"
  },
  {
    locationID: "7",
    locationName: "Wellness Center C",
    specialities: "Orthopedics, Internal Medicine",
    Address: "789 Oak Street",
    city: "Villageville",
    state: "Stateville",
    zipcode: "54321",
    contact: "555-456-7890",
    status: "<CustomSwitch checked={true} />",
    action: "<ModeEditOutlineOutlinedIcon />",
    departmentAdmin:"Austin Richard"
  },
  {
    locationID: "8",
    locationName: "Wellness Center C",
    specialities: "Orthopedics, Internal Medicine",
    Address: "789 Oak Street",
    city: "Villageville",
    state: "Stateville",
    zipcode: "54321",
    contact: "555-456-7890",
    status: "<CustomSwitch checked={true} />",
    action: "<ModeEditOutlineOutlinedIcon />",
    departmentAdmin:"Austin Richard"
  },
  {
    locationID: "9",
    locationName: "Wellness Center C",
    specialities: "Orthopedics, Internal Medicine",
    Address: "789 Oak Street",
    city: "Villageville",
    state: "Stateville",
    zipcode: "54321",
    contact: "555-456-7890",
    status: "<CustomSwitch checked={true} />",
    action: "<ModeEditOutlineOutlinedIcon />",
    departmentAdmin:"Austin Richard"
  },
  {
    locationID: "10",
    locationName: "Wellness Center C",
    specialities: "Orthopedics, Internal Medicine",
    Address: "789 Oak Street",
    city: "Villageville",
    state: "Stateville",
    zipcode: "54321",
    contact: "555-456-7890",
    status: "<CustomSwitch checked={true} />",
    action: "<ModeEditOutlineOutlinedIcon />",
    departmentAdmin:"Austin Richard"
  }
];

