export const readyForBillingList = [
    {
        patientId: "73557",
        visitId: "7171",
        dateofservice: "Fri Nov 12 2023",
        patientName: "Annie Effertz",
        providerName: "Henna West",
        appointmentType: 'New',
        reason: "Fever",
        serviceLocation: 'Location 1',
        action: "Action"
    },
    {
        patientId: "43156",
        visitId: "7392",
        dateofservice: "Sun Dec 3 2023",
        patientName: "Grant Bartoletti",
        providerName: "Mary Riddle",
        appointmentType: 'New',
        reason: "Skin Infection",
        serviceLocation: 'Location 2',
        action: "Action"
    },
    {
        patientId: "65435",
        visitId: "8767",
        dateofservice: "Mon Jan 23 2023",
        patientName: "Loretta Ratke",
        providerName: "Ludo Bagman",
        appointmentType: 'New',
        reason: "Infection Disease",
        serviceLocation: 'Location 3',
        action: "Action"
    },
    {
        patientId: "65345",
        visitId: "3456",
        dateofservice: "Tue Jun 13 2023",
        patientName: "Ginny Weasley",
        providerName: "Ron Wisllie",
        appointmentType: 'New',
        reason: "Skin Infection",
        serviceLocation: 'Location 1',
        action: "Action"
    },
    {
        patientId: "98765",
        visitId: "7623",
        dateofservice: "Fri Nov 12 2023",
        patientName: "Harry Potter",
        providerName: "Ginny Weasley",
        appointmentType: 'New',
        reason: "Fever",
        serviceLocation: 'Location 2',
        action: "Action"
    },
    {
        patientId: "48234",
        visitId: "5623",
        dateofservice: "Tue Jun 13 2023",
        patientName: "Ron Wisllie",
        providerName: "Ludo Bagman",
        appointmentType: 'New',
        reason: "Infection Disease",
        serviceLocation: 'Location 3',
        action: "Action"
    },
    {
        patientId: "65234",
        visitId: "9845",
        dateofservice: "Fri Nov 12 2023",
        patientName: "Annie Effertz",
        providerName: "Harry Potter",
        appointmentType: 'New',
        reason: "Fever",
        serviceLocation: 'Location 4',
        action: "Action"
    },
    {
        patientId: "24853",
        visitId: "7634",
        dateofservice: "Tue Jun 13 2023",
        patientName: "Loretta Ratke",
        providerName: "Annie Effertz",
        appointmentType: 'New',
        reason: "Infection Disease",
        serviceLocation: 'Location 5',
        action: "Action",
    },
    {
        patientId: "84567",
        visitId: "5423",
        dateofservice: "Tue Jun 13 2023",
        patientName: "Annie Effertz",
        providerName: "Ludo Bagman",
        appointmentType: 'New',
        reason: "Skin Infection",
        serviceLocation: 'Location 6',
        action: "Action"
    },
    {
        patientId: "98453",
        visitId: "7645",
        dateofservice: "Fri Nov 12 2023",
        patientName: "Annie Effertz",
        providerName: "Ginny Weasley",
        appointmentType: 'New',
        reason: "Infection Disease",
        serviceLocation: 'Location 7',
        action: "Action"
    },
]