export const referralOut = {
  content: [
    {
      patientName: "Henna Waist",
      avatar:
        "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      contact: "88234293434",
      email: "abc@mailinator.com",
      referralFrom: "Dr.Corina",
      referralFromType: "Primary Provider",
      referralTo: "Kevin Wilson",
      referralToType: "Neurologist",
      date: "04-10-2022",
      status: "Pending",
      action: true,
    },
    {
      patientName: "Henna Waist",
      avatar:
        "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      contact: "88234293434",
      email: "abc@mailinator.com",
      referralFrom: "Dr.Corina",
      referralFromType: "Primary Provider",
      referralTo: "Kevin Wilson",
      referralToType: "Neurologist",
      date: "04-10-2022",
      status: "Pending",
      action: true,
    },
    {
      patientName: "Henna Waist",
      avatar:
        "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      contact: "88234293434",
      email: "abc@mailinator.com",
      referralFrom: "Dr.Corina",
      referralFromType: "Primary Provider",
      referralTo: "Kevin Wilson",
      referralToType: "Neurologist",
      date: "04-10-2022",
      status: "Pending",
      action: true,
    },
    {
      patientName: "Henna Waist",
      avatar:
        "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      contact: "88234293434",
      email: "abc@mailinator.com",
      referralFrom: "Dr.Corina",
      referralFromType: "Primary Provider",
      referralTo: "Kevin Wilson",
      referralToType: "Neurologist",
      date: "04-10-2022",
      status: "Pending",
      action: true,
    },
    {
      patientName: "Henna Waist",
      avatar:
        "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      contact: "88234293434",
      email: "abc@mailinator.com",
      referralFrom: "Dr.Corina",
      referralFromType: "Primary Provider",
      referralTo: "Kevin Wilson",
      referralToType: "Neurologist",
      date: "04-10-2022",
      status: "Pending",
      action: true,
    },
    {
      patientName: "Henna Waist",
      avatar:
        "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      contact: "88234293434",
      email: "abc@mailinator.com",
      referralFrom: "Dr.Corina",
      referralFromType: "Primary Provider",
      referralTo: "Kevin Wilson",
      referralToType: "Neurologist",
      date: "04-10-2022",
      status: null,
      action: true,
    },
    {
      patientName: "Henna Waist",
      avatar:
        "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      contact: "88234293434",
      email: "abc@mailinator.com",
      referralFrom: "Dr.Corina",
      referralFromType: "Primary Provider",
      referralTo: "Kevin Wilson",
      referralToType: "Neurologist",
      date: "04-10-2022",
      status: null,
      action: true,
    },
    {
      patientName: "Henna Waist",
      avatar:
        "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      contact: "88234293434",
      email: "abc@mailinator.com",
      referralFrom: "Dr.Corina",
      referralFromType: "Primary Provider",
      referralTo: "Kevin Wilson",
      referralToType: "Neurologist",
      date: "04-10-2022",
      status: "Pending",
      action: true,
    },
    {
      patientName: "Henna Waist",
      avatar:
        "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      contact: "88234293434",
      email: "abc@mailinator.com",
      referralFrom: "Dr.Corina",
      referralFromType: "Primary Provider",
      referralTo: "Kevin Wilson",
      referralToType: "Neurologist",
      date: "04-10-2022",
      status: "Pending",
      action: true,
    },
    {
      patientName: "Henna Waist",
      avatar:
        "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      contact: "88234293434",
      email: "abc@mailinator.com",
      referralFrom: "Dr.Corina",
      referralFromType: "Primary Provider",
      referralTo: "Kevin Wilson",
      referralToType: "Neurologist",
      date: "04-10-2022",
      status: "Pending",
      action: true,
    },
    {
      patientName: "Henna Waist",
      avatar:
        "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      contact: "88234293434",
      email: "abc@mailinator.com",
      referralFrom: "Dr.Corina",
      referralFromType: "Primary Provider",
      referralTo: "Kevin Wilson",
      referralToType: "Neurologist",
      date: "04-10-2022",
      status: null,
      action: true,
    },
    {
      patientName: "Henna Waist",
      avatar:
        "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
      contact: "88234293434",
      email: "abc@mailinator.com",
      referralFrom: "Dr.Corina",
      referralFromType: "Primary Provider",
      referralTo: "Kevin Wilson",
      referralToType: "Neurologist",
      date: "04-10-2022",
      status: "Pending",
      action: true,
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};
