export const AppointmentReportData = {
  content: [
    {
      date: "26-10-2022",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      location: "Location1",
      room: "room1",
      AppointmentStatus: "In Exam Room",
      BillingStatus: "Paid In Full",
      icdCode: "A04.08-Other bacterial intestinal infection",
      cptCode: "10021-General Surgical Procedures",
    },
    {
      date: "26-10-2022",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      provider: "Provider",
      location: "Location1",
      room: "room1",
      AppointmentStatus: "In Exam Room",
      BillingStatus: "Paid In Full",
      icdCode: "A04.08-Other bacterial intestinal infection",
      cptCode: "10021-General Surgical Procedures",
    },
    {
      date: "26-10-2022",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      provider: "Provider",
      location: "Location1",
      room: "room1",
      AppointmentStatus: "In Exam Room",
      BillingStatus: "Paid In Full",
      icdCode: "A04.08-Other bacterial intestinal infection",
      cptCode: "10021-General Surgical Procedures",
    },
    {
      date: "26-10-2022",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      provider: "Provider",
      location: "Location1",
      room: "room1",
      AppointmentStatus: "In Exam Room",
      BillingStatus: "Paid In Full",
      icdCode: "A04.08-Other bacterial intestinal infection",
      cptCode: "10021-General Surgical Procedures",
    },
    {
      date: "26-10-2022",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      provider: "Provider",
      location: "Location1",
      room: "room1",
      AppointmentStatus: "In Exam Room",
      BillingStatus: "Paid In Full",
      icdCode: "A04.08-Other bacterial intestinal infection",
      cptCode: "10021-General Surgical Procedures",
    },
    {
      date: "26-10-2022",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      provider: "Provider",
      location: "Location1",
      room: "room1",
      AppointmentStatus: "In Exam Room",
      BillingStatus: "Paid In Full",
      icdCode: "A04.08-Other bacterial intestinal infection",
      cptCode: "10021-General Surgical Procedures",
    },
    {
      date: "26-10-2022",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      provider: "Provider",
      location: "Location1",
      room: "room1",
      AppointmentStatus: "In Exam Room",
      BillingStatus: "Paid In Full",
      icdCode: "A04.08-Other bacterial intestinal infection",
      cptCode: "10021-General Surgical Procedures",
    },
    {
      date: "26-10-2022",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      provider: "Provider",
      location: "Location1",
      room: "room1",
      AppointmentStatus: "In Exam Room",
      BillingStatus: "Paid In Full",
      icdCode: "A04.08-Other bacterial intestinal infection",
      cptCode: "10021-General Surgical Procedures",
    },
    {
      date: "26-10-2022",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      provider: "Provider",
      location: "Location1",
      room: "room1",
      AppointmentStatus: "In Exam Room",
      BillingStatus: "Paid In Full",
      icdCode: "A04.08-Other bacterial intestinal infection",
      cptCode: "10021-General Surgical Procedures",
    },
    {
      date: "26-10-2022",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      provider: "Provider",
      location: "Location1",
      room: "room1",
      AppointmentStatus: "In Exam Room",
      BillingStatus: "Paid In Full",
      icdCode: "A04.08-Other bacterial intestinal infection",
      cptCode: "10021-General Surgical Procedures",
    },
    ,
    {
      date: "26-10-2022",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      provider: "Provider",
      location: "Location1",
      room: "room1",
      AppointmentStatus: "In Exam Room",
      BillingStatus: "Paid In Full",
      icdCode: "A04.08-Other bacterial intestinal infection",
      cptCode: "10021-General Surgical Procedures",
    },
    {
      date: "26-10-2022",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      provider: "Provider",
      location: "Location1",
      room: "room1",
      AppointmentStatus: "In Exam Room",
      BillingStatus: "Paid In Full",
      icdCode: "A04.08-Other bacterial intestinal infection",
      cptCode: "10021-General Surgical Procedures",
    },
    {
      date: "26-10-2022",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      provider: "Provider",
      location: "Location1",
      room: "room1",
      AppointmentStatus: "In Exam Room",
      BillingStatus: "Paid In Full",
      icdCode: "A04.08-Other bacterial intestinal infection",
      cptCode: "10021-General Surgical Procedures",
    },
    {
      date: "26-10-2022",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      provider: "Provider",
      location: "Location1",
      room: "room1",
      AppointmentStatus: "In Exam Room",
      BillingStatus: "Paid In Full",
      icdCode: "A04.08-Other bacterial intestinal infection",
      cptCode: "10021-General Surgical Procedures",
    },
    {
      date: "26-10-2022",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      provider: "Provider",
      location: "Location1",
      room: "room1",
      AppointmentStatus: "In Exam Room",
      BillingStatus: "Paid In Full",
      icdCode: "A04.08-Other bacterial intestinal infection",
      cptCode: "10021-General Surgical Procedures",
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};

export const PatientReportData = {
  content: [
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      age: "24 yrs",
      dob: "14-07-1998",
      gender: "Female",
      email: "abc@mailinator.com",
      contact: "84589845684",
      insuranceName: "10021-General",
      language: "Marathi",
      recorded: "Tue Mar 01 2022",
      status: "Active",
    },
    {
    patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      age: "24 yrs",
      dob: "14-07-1998",
      gender: "Female",
      email: "abc@mailinator.com",
      contact: "84589845684",
      insuranceName: "10021-General",
      language: "Marathi",
      recorded: "Tue Mar 01 2022",
      status: "Active",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      age: "24 yrs",
      dob: "14-07-1998",
      gender: "Female",
      email: "abc@mailinator.com",
      contact: "84589845684",
      insuranceName: "10021-General",
      language: "Marathi",
      recorded: "Tue Mar 01 2022",
      status: "Active",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      age: "24 yrs",
      dob: "14-07-1998",
      gender: "Female",
      email: "abc@mailinator.com",
      contact: "84589845684",
      insuranceName: "10021-General",
      language: "Marathi",
      recorded: "Tue Mar 01 2022",
      status: "Active",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      age: "24 yrs",
      dob: "14-07-1998",
      gender: "Female",
      email: "abc@mailinator.com",
      contact: "84589845684",
      insuranceName: "10021-General",
      language: "Marathi",
      recorded: "Tue Mar 01 2022",
      status: "Active",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      age: "24 yrs",
      dob: "14-07-1998",
      gender: "Female",
      email: "abc@mailinator.com",
      contact: "84589845684",
      insuranceName: "10021-General",
      language: "Marathi",
      recorded: "Tue Mar 01 2022",
      status: "Active",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      age: "24 yrs",
      dob: "14-07-1998",
      gender: "Female",
      email: "abc@mailinator.com",
      contact: "84589845684",
      insuranceName: "10021-General",
      language: "Marathi",
      recorded: "Tue Mar 01 2022",
      status: "Active",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      age: "24 yrs",
      dob: "14-07-1998",
      gender: "Female",
      email: "abc@mailinator.com",
      contact: "84589845684",
      insuranceName: "10021-General",
      language: "Marathi",
      recorded: "Tue Mar 01 2022",
      status: "Active",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      age: "24 yrs",
      dob: "14-07-1998",
      gender: "Female",
      email: "abc@mailinator.com",
      contact: "84589845684",
      insuranceName: "10021-General",
      language: "Marathi",
      recorded: "Tue Mar 01 2022",
      status: "Active",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      age: "24 yrs",
      dob: "14-07-1998",
      gender: "Female",
      email: "abc@mailinator.com",
      contact: "84589845684",
      insuranceName: "10021-General",
      language: "Marathi",
      recorded: "Tue Mar 01 2022",
      status: "Active",
    },
    ,
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      age: "24 yrs",
      dob: "14-07-1998",
      gender: "Female",
      email: "abc@mailinator.com",
      contact: "84589845684",
      insuranceName: "10021-General",
      language: "Marathi",
      recorded: "Tue Mar 01 2022",
      status: "Active",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      age: "24 yrs",
      dob: "14-07-1998",
      gender: "Female",
      email: "abc@mailinator.com",
      contact: "84589845684",
      insuranceName: "10021-General",
      language: "Marathi",
      recorded: "Tue Mar 01 2022",
      status: "Active",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      age: "24 yrs",
      dob: "14-07-1998",
      gender: "Female",
      email: "abc@mailinator.com",
      contact: "84589845684",
      insuranceName: "10021-General",
      language: "Marathi",
      recorded: "Tue Mar 01 2022",
      status: "Active",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      age: "24 yrs",
      dob: "14-07-1998",
      gender: "Female",
      email: "abc@mailinator.com",
      contact: "84589845684",
      insuranceName: "10021-General",
      language: "Marathi",
      recorded: "Tue Mar 01 2022",
      status: "Active",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      age: "24 yrs",
      dob: "14-07-1998",
      gender: "Female",
      email: "abc@mailinator.com",
      contact: "84589845684",
      insuranceName: "10021-General",
      language: "Marathi",
      recorded: "Tue Mar 01 2022",
      status: "Active",
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};

export const MedicationReportData = {
  content: [
    {
    patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      age: "24 yrs",
      dob: "14-07-1998",
      gender: "Female",
      email: "abc@mailinator.com",
      contact: "84589845684",
      insuranceName: "10021-General",
      language: "Marathi",
      recorded: "Tue Mar 01 2022",
      status: "Active",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      medications: "buprofen 200 mg oral capsule",
      status: "Active",
      prescribedBy: "Evelyn Parker",
      startDate: "Tue Mar 01 2022",
      endDate: "Fri Mar 15 2022",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      medications: "buprofen 200 mg oral capsule",
      status: "Active",
      prescribedBy: "Evelyn Parker",
      startDate: "Tue Mar 01 2022",
      endDate: "Fri Mar 15 2022",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      medications: "NuvaRing 0.120 mg-0.015 mg/24 hours vaginal ring",
      status: "Active",
      prescribedBy: "Evelyn Parker",
      startDate: "Tue Mar 01 2022",
      endDate: "Fri Mar 15 2022",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      medications: "buprofen 200 mg oral capsule",
      status: "Active",
      prescribedBy: "Evelyn Parker",
      startDate: "Tue Mar 01 2022",
      endDate: "Fri Mar 15 2022",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      medications: "buprofen 200 mg oral capsule",
      status: "Active",
      prescribedBy: "Evelyn Parker",
      startDate: "Tue Mar 01 2022",
      endDate: "Fri Mar 15 2022",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      medications: "buprofen 200 mg oral capsule",
      status: "Active",
      prescribedBy: "Evelyn Parker",
      startDate: "Tue Mar 01 2022",
      endDate: "Fri Mar 15 2022",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      medications: "buprofen 200 mg oral capsule",
      status: "Active",
      prescribedBy: "Evelyn Parker",
      startDate: "Tue Mar 01 2022",
      endDate: "Fri Mar 15 2022",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      medications: "buprofen 200 mg oral capsule",
      status: "Active",
      prescribedBy: "Evelyn Parker",
      startDate: "Tue Mar 01 2022",
      endDate: "Fri Mar 15 2022",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      medications: "buprofen 200 mg oral capsule",
      status: "Active",
      prescribedBy: "Evelyn Parker",
      startDate: "Tue Mar 01 2022",
      endDate: "Fri Mar 15 2022",
    },
    ,
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      medications: "buprofen 200 mg oral capsule",
      status: "Active",
      prescribedBy: "Evelyn Parker",
      startDate: "Tue Mar 01 2022",
      endDate: "Fri Mar 15 2022",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      medications: "buprofen 200 mg oral capsule",
      status: "Active",
      prescribedBy: "Evelyn Parker",
      startDate: "Tue Mar 01 2022",
      endDate: "Fri Mar 15 2022",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      medications: "buprofen 200 mg oral capsule",
      status: "Active",
      prescribedBy: "Evelyn Parker",
      startDate: "Tue Mar 01 2022",
      endDate: "Fri Mar 15 2022",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      medications: "buprofen 200 mg oral capsule",
      status: "Active",
      prescribedBy: "Evelyn Parker",
      startDate: "Tue Mar 01 2022",
      endDate: "Fri Mar 15 2022",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      medications: "buprofen 200 mg oral capsule",
      status: "Active",
      prescribedBy: "Evelyn Parker",
      startDate: "Tue Mar 01 2022",
      endDate: "Fri Mar 15 2022",
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};

export const ProblemReportData = {
  content: [
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      problem: "buprofen 200 mg oral capsule",
      icd10: "Z98.890",
      status: "Active",
      diagnosedDate: "Tue Mar 01 2022",
      updatedDate: "Fri Mar 15 2022",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      problem: "buprofen 200 mg oral capsule",
      icd10: "Z98.890",
      status: "Active",
      diagnosedDate: "Tue Mar 01 2022",
      updatedDate: "Fri Mar 15 2022",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      problem: "buprofen 200 mg oral capsule",
      icd10: "Z98.890",
      status: "Active",
      diagnosedDate: "Tue Mar 01 2022",
      updatedDate: "Fri Mar 15 2022",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      problem: "buprofen 200 mg oral capsule",
      icd10: "Z98.890",
      status: "Active",
      diagnosedDate: "Tue Mar 01 2022",
      updatedDate: "Fri Mar 15 2022",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      problem: "buprofen 200 mg oral capsule",
      icd10: "Z98.890",
      status: "Active",
      diagnosedDate: "Tue Mar 01 2022",
      updatedDate: "Fri Mar 15 2022",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      problem: "buprofen 200 mg oral capsule",
      icd10: "Z98.890",
      status: "Active",
      diagnosedDate: "Tue Mar 01 2022",
      updatedDate: "Fri Mar 15 2022",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      problem: "buprofen 200 mg oral capsule",
      icd10: "Z98.890",
      status: "Active",
      diagnosedDate: "Tue Mar 01 2022",
      updatedDate: "Fri Mar 15 2022",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      problem: "buprofen 200 mg oral capsule",
      icd10: "Z98.890",
      status: "Active",
      diagnosedDate: "Tue Mar 01 2022",
      updatedDate: "Fri Mar 15 2022",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      problem: "buprofen 200 mg oral capsule",
      icd10: "Z98.890",
      status: "Active",
      diagnosedDate: "Tue Mar 01 2022",
      updatedDate: "Fri Mar 15 2022",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      problem: "buprofen 200 mg oral capsule",
      icd10: "Z98.890",
      status: "Active",
      diagnosedDate: "Tue Mar 01 2022",
      updatedDate: "Fri Mar 15 2022",
    },
    ,
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      problem: "buprofen 200 mg oral capsule",
      icd10: "Z98.890",
      status: "Active",
      diagnosedDate: "Tue Mar 01 2022",
      updatedDate: "Fri Mar 15 2022",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      problem: "buprofen 200 mg oral capsule",
      icd10: "Z98.890",
      status: "Active",
      diagnosedDate: "Tue Mar 01 2022",
      updatedDate: "Fri Mar 15 2022",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      problem: "buprofen 200 mg oral capsule",
      icd10: "Z98.890",
      status: "Active",
      diagnosedDate: "Tue Mar 01 2022",
      updatedDate: "Fri Mar 15 2022",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      problem: "buprofen 200 mg oral capsule",
      icd10: "Z98.890",
      status: "Active",
      diagnosedDate: "Tue Mar 01 2022",
      updatedDate: "Fri Mar 15 2022",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      problem: "buprofen 200 mg oral capsule",
      icd10: "Z98.890",
      status: "Active",
      diagnosedDate: "Tue Mar 01 2022",
      updatedDate: "Fri Mar 15 2022",
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};

export const AllergyReportData = {
  content: [
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      allery: "No Known Drug Allergies (NKDA)",
      reaction: "Shortness of breath/difficulty breathing",
      severity: "Mild",
      status: "Active",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      allery: "No Known Drug Allergies (NKDA)",
      reaction: "Shortness of breath/difficulty breathing",
      severity: "Mild",
      status: "Active",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      allery: "No Known Drug Allergies (NKDA)",
      reaction: "Shortness of breath/difficulty breathing",
      severity: "Mild",
      status: "Active",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      allery: "No Known Drug Allergies (NKDA)",
      reaction: "Shortness of breath/difficulty breathing",
      severity: "Mild",
      status: "Active",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      allery: "No Known Drug Allergies (NKDA)",
      reaction: "Shortness of breath/difficulty breathing",
      severity: "Mild",
      status: "Active",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      allery: "No Known Drug Allergies (NKDA)",
      reaction: "Shortness of breath/difficulty breathing",
      severity: "Mild",
      status: "Active",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      allery: "No Known Drug Allergies (NKDA)",
      reaction: "Shortness of breath/difficulty breathing",
      severity: "Mild",
      status: "Active",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      allery: "No Known Drug Allergies (NKDA)",
      reaction: "Shortness of breath/difficulty breathing",
      severity: "Mild",
      status: "Active",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      allery: "No Known Drug Allergies (NKDA)",
      reaction: "Shortness of breath/difficulty breathing",
      severity: "Mild",
      status: "Active",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      allery: "No Known Drug Allergies (NKDA)",
      reaction: "Shortness of breath/difficulty breathing",
      severity: "Mild",
      status: "Active",
    },
    ,
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      allery: "No Known Drug Allergies (NKDA)",
      reaction: "Shortness of breath/difficulty breathing",
      severity: "Mild",
      status: "Active",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      allery: "No Known Drug Allergies (NKDA)",
      reaction: "Shortness of breath/difficulty breathing",
      severity: "Mild",
      status: "Active",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      allery: "No Known Drug Allergies (NKDA)",
      reaction: "Shortness of breath/difficulty breathing",
      severity: "Mild",
      status: "Active",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      allery: "No Known Drug Allergies (NKDA)",
      reaction: "Shortness of breath/difficulty breathing",
      severity: "Mild",
      status: "Active",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      dob: "14-07-1998",
      allery: "No Known Drug Allergies (NKDA)",
      reaction: "Shortness of breath/difficulty breathing",
      severity: "Mild",
      status: "Active",
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};

export const PIAReportData = {
  content: [
    {
      authorization:"735574587",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      procedureCodes: "90846",
      sdate:"12-09-1999",
      edate:"12-09-1999",
      speciality: "Multi-speciality",
      approved: "8",
      remaining: "3",
      status: "Active",
    },
    {
      authorization:"735574587",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      procedureCodes: "90846",
      sdate:"12-09-1999",
      edate:"12-09-1999",
      speciality: "Multi-speciality",
      approved: "8",
      remaining: "3",
      status: "Active",
    },
    {
      authorization:"735574587",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      procedureCodes: "90846",
      sdate:"12-09-1999",
      edate:"12-09-1999",
      speciality: "Multi-speciality",
      approved: "8",
      remaining: "3",
      status: "Active",
    },
    {
      authorization:"735574587",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      procedureCodes: "90846",
      sdate:"12-09-1999",
      edate:"12-09-1999",
      speciality: "Multi-speciality",
      approved: "8",
      remaining: "3",
      status: "Active",
    },
    {
      authorization:"735574587",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      procedureCodes: "90846",
      sdate:"12-09-1999",
      edate:"12-09-1999",
      speciality: "Multi-speciality",
      approved: "8",
      remaining: "3",
      status: "Active",
    },
    {
      authorization:"735574587",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      procedureCodes: "90846",
      sdate:"12-09-1999",
      edate:"12-09-1999",
      speciality: "Multi-speciality",
      approved: "8",
      remaining: "3",
      status: "Active",
    },
    {
      authorization:"735574587",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      procedureCodes: "90846",
      sdate:"12-09-1999",
      edate:"12-09-1999",
      speciality: "Multi-speciality",
      approved: "8",
      remaining: "3",
      status: "Active",
    },
    {
      authorization:"735574587",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      procedureCodes: "90846",
      sdate:"12-09-1999",
      edate:"12-09-1999",
      speciality: "Multi-speciality",
      approved: "8",
      remaining: "3",
      status: "Active",
    },
    {
      authorization:"735574587",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      procedureCodes: "90846",
      sdate:"12-09-1999",
      edate:"12-09-1999",
      speciality: "Multi-speciality",
      approved: "8",
      remaining: "3",
      status: "Active",
    },
    {
      authorization:"735574587",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      procedureCodes: "90846",
      sdate:"12-09-1999",
      edate:"12-09-1999",
      speciality: "Multi-speciality",
      approved: "8",
      remaining: "3",
      status: "Active",
    },
    ,
    {
      authorization:"735574587",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      procedureCodes: "90846",
      sdate:"12-09-1999",
      edate:"12-09-1999",
      speciality: "Multi-speciality",
      approved: "8",
      remaining: "3",
      status: "Active",
    },
    {
      authorization:"735574587",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      procedureCodes: "90846",
      sdate:"12-09-1999",
      edate:"12-09-1999",
      speciality: "Multi-speciality",
      approved: "8",
      remaining: "3",
      status: "Active",
    },
    {
      authorization:"735574587",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      procedureCodes: "90846",
      sdate:"12-09-1999",
      edate:"12-09-1999",
      speciality: "Multi-speciality",
      approved: "8",
      remaining: "3",
      status: "Active",
    },
    {
      authorization:"735574587",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      procedureCodes: "90846",
      sdate:"12-09-1999",
      edate:"12-09-1999",
      speciality: "Multi-speciality",
      approved: "8",
      remaining: "3",
      status: "Active",
    },
    {
      authorization:"735574587",
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      procedureCodes: "90846",
      sdate:"12-09-1999",
      edate:"12-09-1999",
      speciality: "Multi-speciality",
      approved: "8",
      remaining: "3",
      status: "Active",
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};

export const EncounterReportData = {
  content: [
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      date:"14-12-2000",
      visitType:"In-Person",
      renderingProvider:"Dr. Corina",
      signedProvider:"Ronald Jackson",
      signedDate:"20-12-1998",
      status: "Waitting Room",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      date:"14-12-2000",
      visitType:"In-Person",
      renderingProvider:"Dr. Corina",
      signedProvider:"Ronald Jackson",
      signedDate:"20-12-1998",
      status: "Waitting Room",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      date:"14-12-2000",
      visitType:"In-Person",
      renderingProvider:"Dr. Corina",
      signedProvider:"Ronald Jackson",
      signedDate:"20-12-1998",
      status: "Waitting Room",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      date:"14-12-2000",
      visitType:"In-Person",
      renderingProvider:"Dr. Corina",
      signedProvider:"Ronald Jackson",
      signedDate:"20-12-1998",
      status: "Waitting Room",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      date:"14-12-2000",
      visitType:"In-Person",
      renderingProvider:"Dr. Corina",
      signedProvider:"Ronald Jackson",
      signedDate:"20-12-1998",
      status: "Waitting Room",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      date:"14-12-2000",
      visitType:"In-Person",
      renderingProvider:"Dr. Corina",
      signedProvider:"Ronald Jackson",
      signedDate:"20-12-1998",
      status: "Waitting Room",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      date:"14-12-2000",
      visitType:"In-Person",
      renderingProvider:"Dr. Corina",
      signedProvider:"Ronald Jackson",
      signedDate:"20-12-1998",
      status: "Waitting Room",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      date:"14-12-2000",
      visitType:"In-Person",
      renderingProvider:"Dr. Corina",
      signedProvider:"Ronald Jackson",
      signedDate:"20-12-1998",
      status: "Waitting Room",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      date:"14-12-2000",
      visitType:"In-Person",
      renderingProvider:"Dr. Corina",
      signedProvider:"Ronald Jackson",
      signedDate:"20-12-1998",
      status: "Waitting Room",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      date:"14-12-2000",
      visitType:"In-Person",
      renderingProvider:"Dr. Corina",
      signedProvider:"Ronald Jackson",
      signedDate:"20-12-1998",
      status: "Waitting Room",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      date:"14-12-2000",
      visitType:"In-Person",
      renderingProvider:"Dr. Corina",
      signedProvider:"Ronald Jackson",
      signedDate:"20-12-1998",
      status: "Waitting Room",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      date:"14-12-2000",
      visitType:"In-Person",
      renderingProvider:"Dr. Corina",
      signedProvider:"Ronald Jackson",
      signedDate:"20-12-1998",
      status: "Waitting Room",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      date:"14-12-2000",
      visitType:"In-Person",
      renderingProvider:"Dr. Corina",
      signedProvider:"Ronald Jackson",
      signedDate:"20-12-1998",
      status: "Waitting Room",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      date:"14-12-2000",
      visitType:"In-Person",
      renderingProvider:"Dr. Corina",
      signedProvider:"Ronald Jackson",
      signedDate:"20-12-1998",
      status: "Waitting Room",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      date:"14-12-2000",
      visitType:"In-Person",
      renderingProvider:"Dr. Corina",
      signedProvider:"Ronald Jackson",
      signedDate:"20-12-1998",
      status: "Waitting Room",
    },
    {
      patientId: "A424",
      firstName: "Henna",
      lastName: "Topical",
      date:"14-12-2000",
      visitType:"In-Person",
      renderingProvider:"Dr. Corina",
      signedProvider:"Ronald Jackson",
      signedDate:"20-12-1998",
      status: "Waitting Room",
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};