export const SocialHistory = {
    content: [
      {
        title: "Asthama",
        form: "brother",
        answer: "17",
        recordeddate: "04-10-2022",
        action: true,
      },
      {
        title: "Asthama",
        form: "brother",
        answer: "8points-mild",
        recordeddate: "04-10-2022",
        action: true,
      },
      {
        title: "Asthama",
        form: "brother",
        answer: "8points-mild",
        recordeddate: "04-10-2022",
        action: true,
      },
      {
        title: "Asthama",
        form: "brother",
        answer: "8points-mild",
        recordeddate: "04-10-2022",
        action: true,
      },
      {
        title: "Asthama",
        form: "brother",
        answer: "8points-mild",
        recordeddate: "04-10-2022",
        action: true,
      },
      {
        title: "Asthama",
        form: "brother",
        answer: "8points-mild",
        recordeddate: "04-10-2022",
        action: true,
      },
      {
        title: "Asthama",
        form: "brother",
        answer: "8points-mild",
        recordeddate: "04-10-2022",
        action: true,
      },
      {
        title: "Asthama",
        form: "brother",
        answer: "8points-mild",
        recordeddate: "04-10-2022",
        action: true,
      },
      {
        title: "Asthama",
        form: "brother",
        answer: "8points-mild",
        recordeddate: "04-10-2022",
        action: true,
      },
      {
        title: "Asthama",
        form: "brother",
        answer: "8points-mild",
        recordeddate: "04-10-2022",
        action: true,
      },
      {
        title: "Asthama",
        form: "brother",
        answer: "8points-mild",
        recordeddate: "04-10-2022",
        action: true,
      },
      {
        title: "Asthama",
        form: "brother",
        answer: "8points-mild",
        recordeddate: "04-10-2022",
        action: true,
      },
    ],
    pageable: {
      sort: [
        {
          direction: "DESC",
          property: "created",
          ignoreCase: false,
          nullHandling: "NATIVE",
          ascending: false,
          descending: true,
        },
      ],
      offset: 0,
      pageNumber: 0,
      pageSize: 10,
      paged: true,
      unpaged: false,
    },
    totalPages: 1,
    totalElements: 3,
    last: true,
    size: 10,
    number: 0,
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    numberOfElements: 1,
    first: true,
    empty: false,
  };
  