export const superBillList = [
    {
        billId: "73557",
        patientId: "7171",
        patientName: "Annie Effertz",
        visitDate: "Fri Nov 12 2023",
        reason: "Fever",
        provider: "Henna West",
        billingStatus: "Pending",
        action: "Action",
    },
    {
        billId: "43156",
        patientId: "7392",
        patientName: "Grant Bartoletti",
        visitDate: "Sun Dec 3 2023",
        reason: "Skin Infection",
        provider: "Mary Riddle",
        billingStatus: "Completed",
        action: "Action",
    },
    {
        billId: "65435",
        patientId: "8767",
        patientName: "Loretta Ratke",
        visitDate: "Mon Jan 23 2023",
        reason: "Infection Disease",
        provider: "Ludo Bagman",
        billingStatus: "Inprogress",
        action: "Action",
    },
    {
        billId: "65345",
        patientId: "3456",
        patientName: "Ginny Weasley",
        visitDate: "Tue Jun 13 2023",
        reason: "Skin Infection",
        provider: "Ron Wisllie",
        billingStatus: "Pending",
        action: "Action",
    },
    {
        billId: "98765",
        patientId: "7623",
        patientName: "Harry Potter",
        visitDate: "Fri Nov 12 2023",
        reason: "Fever",
        provider: "Ginny Weasley",
        billingStatus: "Completed",
        action: "Action",
    },
    {
        billId: "48234",
        patientId: "5623",
        patientName: "Ron Wisllie",
        visitDate: "Tue Jun 13 2023",
        reason: "Infection Disease",
        provider: "Ludo Bagman",
        billingStatus: "Inprogress",
        action: "Action",
    },
    {
        billId: "65234",
        patientId: "9845",
        patientName: "Annie Effertz",
        visitDate: "Fri Nov 12 2023",
        reason: "Fever",
        provider: "Harry Potter",
        billingStatus: "Pending",
        action: "Action",
    },
    {
        billId: "24853",
        patientId: "7634",
        patientName: "Loretta Ratke",
        visitDate: "Tue Jun 13 2023",
        reason: "Infection Disease",
        provider: "Annie Effertz",
        billingStatus: "Completed",
        action: "Action",
    },
    {
        billId: "84567",
        patientId: "5423",
        patientName: "Annie Effertz",
        visitDate: "Tue Jun 13 2023",
        reason: "Skin Infection",
        provider: "Ludo Bagman",
        billingStatus: "Inprogress",
        action: "Action",
    },
    {
        billId: "98453",
        patientId: "7645",
        patientName: "Annie Effertz",
        visitDate: "Fri Nov 12 2023",
        reason: "Infection Disease",
        provider: "Ginny Weasley",
        billingStatus: "Completed",
        action: "Action",
    },
]