export const vaccinesforms = {
  content: [
    {
      vaccinename: "COVID-19, MRNA, LNP-S, PF",
      doseduration: "7 Days",
      administerdate: "04-10-2022",
      administeredby: "Delbert Gonzalez",
      expirydate: "26-10-2022",
      amount: "2ml",
      route: "Injection",
      site: "Ankle, Left",
      manufacturer: "Ceva",
      lotnumber: "2345",
      action: true,
    },
    {
      vaccinename: "COVID-19 (SARS-COV-2)",
      doseduration: "10 Days",
      administerdate: "04-10-2022",
      administeredby: "Tim Spencer",
      expirydate: "10-11-2022",
      amount: "1ml",
      route: "Injection",
      site: "Ankle, Right",
      manufacturer: "Janssen",
      lotnumber: "65435",
      action: true,
    },
    {
      vaccinename: "COVID-19, MRNA, LNP-S, PF,",
      doseduration: "25 Days",
      administerdate: "04-10-2022",
      administeredby: "Terrance Shaw",
      expirydate: "26-10-2022",
      amount: "2ml",
      route: "Injection",
      site: "Arm, Left Upper",
      manufacturer: "Aldevron",
      lotnumber: "78345",
      action: true,
    },
    {
      vaccinename: "MENINGOCOCCAL POLYSACCHARIDE",
      doseduration: "20 Days",
      administerdate: "04-10-2022",
      administeredby: "Vincent Dennis",
      expirydate: "26-10-2022",
      amount: "2ml",
      route: "Injection",
      site: "Arm, Left Upper",
      manufacturer: "Kemin",
      lotnumber: "95345",
      action: true,
    },
    {
      vaccinename: "COVID-19, MRNA, LNP-S, PF",
      doseduration: "7 Days",
      administerdate: "04-10-2022",
      administeredby: "Delbert Gonzalez",
      expirydate: "26-10-2022",
      amount: "2ml",
      route: "Injection",
      site: "Ankle, Left",
      manufacturer: "Ceva",
      lotnumber: "2345",
      action: true,
    },
    {
      vaccinename: "COVID-19 (SARS-COV-2)",
      doseduration: "10 Days",
      administerdate: "04-10-2022",
      administeredby: "Tim Spencer",
      expirydate: "10-11-2022",
      amount: "1ml",
      route: "Injection",
      site: "Ankle, Right",
      manufacturer: "Janssen",
      lotnumber: "65435",
      action: true,
    },
    {
      vaccinename: "COVID-19, MRNA, LNP-S, PF,",
      doseduration: "25 Days",
      administerdate: "04-10-2022",
      administeredby: "Terrance Shaw",
      expirydate: "26-10-2022",
      amount: "2ml",
      route: "Injection",
      site: "Arm, Left Upper",
      manufacturer: "Aldevron",
      lotnumber: "78345",
      action: true,
    },
    {
      vaccinename: "MENINGOCOCCAL POLYSACCHARIDE",
      doseduration: "20 Days",
      administerdate: "04-10-2022",
      administeredby: "Vincent Dennis",
      expirydate: "26-10-2022",
      amount: "2ml",
      route: "Injection",
      site: "Arm, Left Upper",
      manufacturer: "Kemin",
      lotnumber: "95345",
      action: true,
    },
    {
      vaccinename: "COVID-19, MRNA, LNP-S, PF",
      doseduration: "7 Days",
      administerdate: "04-10-2022",
      administeredby: "Delbert Gonzalez",
      expirydate: "26-10-2022",
      amount: "2ml",
      route: "Injection",
      site: "Ankle, Left",
      manufacturer: "Ceva",
      lotnumber: "2345",
      action: true,
    },
    {
      vaccinename: "COVID-19 (SARS-COV-2)",
      doseduration: "10 Days",
      administerdate: "04-10-2022",
      administeredby: "Tim Spencer",
      expirydate: "10-11-2022",
      amount: "1ml",
      route: "Injection",
      site: "Ankle, Right",
      manufacturer: "Janssen",
      lotnumber: "65435",
      action: true,
    },
    {
      vaccinename: "COVID-19, MRNA, LNP-S, PF,",
      doseduration: "25 Days",
      administerdate: "04-10-2022",
      administeredby: "Terrance Shaw",
      expirydate: "26-10-2022",
      amount: "2ml",
      route: "Injection",
      site: "Arm, Left Upper",
      manufacturer: "Aldevron",
      lotnumber: "78345",
      action: true,
    },
    {
      vaccinename: "MENINGOCOCCAL POLYSACCHARIDE",
      doseduration: "20 Days",
      administerdate: "04-10-2022",
      administeredby: "Vincent Dennis",
      expirydate: "26-10-2022",
      amount: "2ml",
      route: "Injection",
      site: "Arm, Left Upper",
      manufacturer: "Kemin",
      lotnumber: "95345",
      action: true,
    },
  ],
  pageable: {
    sort: [
      {
        direction: "DESC",
        property: "created",
        ignoreCase: false,
        nullHandling: "NATIVE",
        ascending: false,
        descending: true,
      },
    ],
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  totalPages: 1,
  totalElements: 3,
  last: true,
  size: 10,
  number: 0,
  sort: [
    {
      direction: "DESC",
      property: "created",
      ignoreCase: false,
      nullHandling: "NATIVE",
      ascending: false,
      descending: true,
    },
  ],
  numberOfElements: 1,
  first: true,
  empty: false,
};
