import { makeStyles } from "@mui/material";

export const WaitingStyle = makeStyles({
  screen: {
    backgroundColor: '#dddddd',
    width: '100vw',
    height: '100vh',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    overflowY: 'auto',
    '& .container': {
      display: 'flex',
      alignItems: 'center',
      height: '60%',
      width: '100%',
      flexDirection: 'column',
      justifyContent: 'space-between',
      '& .left': {
        width: '100%',
        display: 'flex',
        justifyContent: 'center',
        height: '90%',
        alignItems: 'center',
        flexDirection: 'column',
        position: 'relative',
        '& .video': {
          width: '60%',
          height: '100%',
          backgroundColor: '#4261c3',
          borderRadius: '2rem',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          textAlign: 'center',
          gap: '25px',
        },
        '& .action': {
          display: 'flex',
          justifyContent: 'center',
          gap: '1rem',
          position: 'relative',
          bottom: '60px',
          width: '100%',
          '& .icon': {
            width: '50px',
            height: '50px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            borderRadius: '50%',
            backgroundColor: 'white',
            color: '#ff0000',
            cursor: 'pointer',
          },
        },
      },
      '& .right': {
        width: '100%',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        '& .permission': {
          display: 'flex',
          flexDirection: 'column',
          width: '60%',
          gap: '13px',
          alignItems: 'center',
          '& .button': {
            cursor: 'pointer',
            backgroundColor: '#b0c21f',
            color: 'white',
            border: '0px solid #4261c3',
            borderRadius: '90px',
            fontSize: '15px',
            fontWeight: '600',
            padding: '1em 1.5em',
          },
        },
      },
    },
  },
  custom: {
    '& video': {
      borderRadius: '8px',
      objectFit: 'cover',
      transform: 'scaleX(-1)',
      position: 'absolute',
    },
    width: '100% !important',
    height: '100% !important',
  },
})